'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert'),R=path.resolve(__dirname,'../..');
new Function('require','__dirname',fs.readFileSync(path.join(__dirname,'cutscene-shared-actor-integration.test.js'),'utf8').split('\n(async()=>')[0])(require,__dirname);
for(const file of ['cutscene-njpg.js','cutscene-dialogue-draw.js','cutscene-captured-continuous-data.js','cutscene-captured-scheduler-data.js','cutscene-captured-scheduler.js'])vm.runInThisContext(fs.readFileSync(path.join(R,'editor',file),'utf8'),{filename:file});
const fixture=require('./fixtures/cutscene-graduation-continuous.json'),observed=require('./fixtures/cutscene-graduation-native.json'),clone=x=>JSON.parse(JSON.stringify(x));
(async()=>{
 const raw=fs.readFileSync(path.join(R,'Ogre Battle 64 - Person of Lordly Caliber (U) [!].v64')),z64=new Uint8Array(raw.length);for(let i=0;i<raw.length;i+=2){z64[i]=raw[i+1];z64[i+1]=raw[i];}
 const rom={z64,archives:OB64.findArchives(z64),layout:{id:'us-rev0'}},ui=OB64.cutsceneUI.initialize(rom),scene=ui.catalog.getScene(fixture.input.assetId),source=await OB64.cutsceneCodec.loadSceneSource(z64,scene),p=OB64.cutsceneCodec.projectSceneDocument(scene,source,ui.catalog);
 const Scheduler=OB64.cutsceneCapturedScheduler,instances=[],Engine=OB64.cutsceneDialogue.Engine,engines=[];
 OB64.cutsceneCapturedScheduler=function(...args){const value=new Scheduler(...args);instances.push(value);return value;};OB64.cutsceneDialogue.Engine=function(...args){const value=new Engine(...args);engines.push(value);return value;};
 const run=(input=fixture.input,options={})=>OB64.cutsceneRuntime.compile(p.document,p.program,scene,ui.catalog,{z64,nativeLaunchInputs:input,diagnosticAssumptions:false,...options});
 const started=performance.now(),original=JSON.stringify(fixture.input),result=run(),compileMs=performance.now()-started,service=instances.at(-1),engine=engines.at(-1);
 assert.equal(result.outcome,'modeled-termination');assert.equal(result.states.length,698);assert.equal(result.unresolvedQuery,null);assert.deepStrictEqual(result.missingInputs,[]);assert.deepStrictEqual(result.assumptions,[]);assert.equal(JSON.stringify(fixture.input),original);assert(Buffer.byteLength(original)<131072);
 assert(result.states.every(s=>s.actors.length===8));assert.equal(service.actorComparisons,698*8);assert.equal(service.dialogueComparisons,1);assert.equal(service.colorComparisons,1);let records=0;
 for(const expected of fixture.expected){const state=result.states[expected.update-1];for(const row of expected.actors){assert.equal(state.actors.find(a=>a.slot===row.slot).source.recordHex,row.recordHex,`Actor ${expected.update}/${row.slot}`);records++;}}
 const bits=n=>{const b=Buffer.alloc(4);b.writeFloatBE(n);return b.toString('hex').toUpperCase();};for(const sample of observed.samples){const actor=result.states[sample.eligibleUpdate-1].actors.find(a=>a.slot===1),native=OB64.cutsceneRuntime.decodeNativeActorState(actor.nativeActorState);assert.equal(bits(actor.baseX),sample.xBits);assert.deepStrictEqual([native.poseCursor,native.poseDelay,actor.displayedFrameToken],sample.pose);}
 const automatic=result.trace.filter(r=>r.kind==='resource-pass').flatMap(r=>r.actions.filter(a=>a.service==='automatic-page-acknowledgement').map(a=>({...a,pass:r.tick})));
 assert.equal(automatic.length,4);for(const ack of automatic){const previous=result.states[ack.pass-1].dialogue.map(d=>d.payload.nativeDialogue);assert(previous.some(d=>d&&[3,6].includes(d.state)));assert.equal(ack.timing,'simulated-next-eligible-pass');}
 const neutral=clone(fixture.input);neutral.capturedResume.value.resourceServices.resourceSchedule.pageAdvancePolicy='neutral';const held=run(neutral);assert.equal(held.outcome,'awaiting-dialogue-input');assert.equal(held.states.length,332);assert.equal(held.unresolvedQuery.code,'dialogue-page-acknowledgement');assert.deepStrictEqual(held.states.map(s=>s.actors),result.states.slice(0,332).map(s=>s.actors));
 const plateau=clone(neutral);plateau.capturedResume.value.updates=350;const continued=run(plateau,{stopAtInputWait:false});assert.equal(continued.states.at(-1).dialogue[0].payload.text,held.states.at(-1).dialogue[0].payload.text);assert.equal(continued.states.at(-1).dialogue[0].payload.nativeDialogue.state,6);
 const one=clone(fixture.input);one.capturedResume.value.updates=1;assert.deepStrictEqual(run(one).states[0].actors,result.states[0].actors);
 const again=run();assert.deepStrictEqual(again.states,result.states);assert.notStrictEqual(again.states[0].actors,result.states[0].actors);
 for(const tick of [0,123,331,584,680,697,331,0])assert.deepStrictEqual(OB64.cutsceneRuntime.evaluate(result,tick).actors,result.states[tick].actors);
 const asynchronous=await OB64.cutsceneRuntime.compileAsync(p.document,p.program,scene,ui.catalog,{z64,nativeLaunchInputs:fixture.input,diagnosticAssumptions:false});assert.deepStrictEqual(asynchronous.states,result.states);
 const cancel=new AbortController(),advance=Engine.prototype.service;let entered=false;Engine.prototype.service=function*(event,...args){if(event.service==='callback'&&this.owners.some(o=>o&&o.payload&&o.payload.length===1144)){entered=true;cancel.abort();}return yield* advance.call(this,event,...args);};
 try{await assert.rejects(OB64.cutsceneRuntime.compileAsync(p.document,p.program,scene,ui.catalog,{z64,nativeLaunchInputs:fixture.input,signal:cancel.signal}),e=>e.name==='AbortError');}finally{Engine.prototype.service=advance;}assert(entered);
 const invalid=clone(fixture.input);invalid.capturedResume.value.resourceServices.resourceSchedule.pageAdvancePolicy='choose-story-answer';assert.notEqual(run(invalid).outcome,'modeled-termination');
 const overlap=clone(fixture.input);overlap.capturedResume.value.resourceServices.colorArena.address=overlap.capturedResume.value.resourceServices.initialDialogue.payloadStorage.address;assert.throws(()=>run(overlap),e=>e.code==='resume-color-arena');
 const missing=clone(fixture.input);missing.capturedResume.value.nativeScheduler.memory=missing.capturedResume.value.nativeScheduler.memory.filter(r=>!(r.address<=0x8018fc10&&r.address+r.hex.length/2>0x8018fc10));assert.throws(()=>run(missing));
 OB64.cutsceneUI.setNativeLaunchInputs(ui,scene,fixture.input);const loadStarted=performance.now();await OB64.cutsceneUI.loadScene(rom,ui,scene);const publicLoadMs=performance.now()-loadStarted;assert.deepStrictEqual(ui.runtimeByAssetId[scene.assetId].states,result.states);assert(OB64.cutsceneUI.playbackTimingLabel(ui,scene).includes('simulated timing'));
 const images={};for(const tick of [331,461,584,622,680,697,331]){const preview=OB64.cutsceneRuntime.evaluate(result,tick),backgrounds=[];for(const layer of preview.background.layers){const asset=ui.catalog.getImageAsset(layer.assetId);if(asset){const image=await OB64.cutsceneUI.decodeImageAsset(rom,ui,asset);assert(image.renderable);backgrounds.push({layer,image});}}
 const actorFrames=OB64.cutsceneSprites.framesForPreview(ui.spriteState,preview),scenePropFrames=OB64.cutsceneSprites.framesForStageProps(ui.spriteState,preview.background.projection,preview.frame);assert.equal(Object.keys(actorFrames).length,8);assert.equal(scenePropFrames.length,12);
 const image=OB64.cutsceneRenderer.renderFrame(p.document,preview,{showMovementPaths:false,backgrounds,backgroundProjection:preview.background.projection,projection:preview.actorProjection,actorFrames,scenePropFrames,effectFrames:[],camera:preview.cameraState,overlays:preview.overlays,colorModulation:preview.sceneColor,screenTransition:preview.screenTransition,sceneVignette:preview.sceneVignette,oversizedImageView:preview.oversizedImageView});
 const dialogue=OB64.cutsceneUI.composeDialogue(rom,ui,preview,true);assert.equal(dialogue.rows.length,preview.dialogue.length);dialogue.rows.forEach(row=>OB64.cutsceneDialogueDraw.paint(image,row));if(images[tick])assert.deepStrictEqual(image.rgba,images[tick]);else images[tick]=image.rgba;
 }
 assert.notDeepStrictEqual(images[331],images[461]);assert.notDeepStrictEqual(images[622],images[697]);
 const serviceBytes=[service.machine,engine.machine].reduce((n,m)=>n+m.regions.reduce((n,r)=>n+r.bytes.length,0),0);assert(serviceBytes<=131072);assert(result.retainedStateBytes<=128*1024*1024);assert(ui.imageCacheBytes<=OB64.cutsceneUI.imageCacheLimit);
 console.log(JSON.stringify({status:'pass',compileMs:Math.round(compileMs),publicLoadMs:Math.round(publicLoadMs),currentActorComparisons:service.actorComparisons,dialogueConstructorBytes:168,colorConstructorBytes:12,automaticPasses:result.states.length,neutralWaitPasses:held.states.length,fullActorRecords:records,acceptedHistoricalSamples:observed.samples.length,automaticAcknowledgements:automatic.map(r=>r.pass),inputBytes:Buffer.byteLength(original),serviceBytes,retainedStateBytes:result.retainedStateBytes,publicImportLoad:true,seekRepeatAsyncParity:true,cancellation:true,composedImages:6,scope:'Modeled termination with simulated automatic acknowledgement; neutral/native prefix kept separate'}));
})().catch(e=>{console.error(e.stack||e);process.exitCode=1;});
