'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert'),R=path.resolve(__dirname,'../..');
const boot=fs.readFileSync(path.join(__dirname,'cutscene-framebuffer-integration.test.js'),'utf8').split('(async()=>')[0];new Function('require','__dirname',boot)(require,__dirname);
for(const f of ['cutscene-image-echo-data.js','cutscene-image-echo.js'])vm.runInThisContext(fs.readFileSync(path.join(R,'editor',f),'utf8'),{filename:f});
(async()=>{
 const v=fs.readFileSync(path.join(R,'Ogre Battle 64 - Person of Lordly Caliber (U) [!].v64')),z64=new Uint8Array(v.length);for(let i=0;i<v.length;i+=2){z64[i]=v[i+1];z64[i+1]=v[i];}
 const rom={z64,archives:OB64.findArchives(z64),layout:{id:'us-rev0'}},state=OB64.cutsceneUI.initialize(rom),input=structuredClone(require('./fixtures/cutscene-image-echo.json').input),before=JSON.stringify(input),scene=state.catalog.getScene(input.assetId);
 assert(Buffer.byteLength(before)<131072);assert.equal(OB64.cutsceneUI.launchContextChoice(state,scene,null).id,'event-director:7:b00A4:invocation:52:context:0');
 OB64.cutsceneUI.setNativeLaunchInputs(state,scene,input);await OB64.cutsceneUI.loadScene(rom,state,scene);const r=state.runtimeByAssetId[scene.assetId];
 assert.equal(JSON.stringify(input),before);assert.equal(r.states.length,1435,JSON.stringify(r.unresolvedQuery));assert.equal(r.unresolvedQuery.code,'transient-menu-constructor');assert.equal(r.trace.filter(t=>t.kind==='resource-pass').length,1434);assert.equal(r.trace.at(-1).nodeId,'node:01F4558C:w03C6');assert.equal(r.states.at(-1).nativeExternal.menus.length,0);assert.equal(r.framebuffers.length,1);assert.equal(r.framebuffers[0].pass,641);assert.equal(r.framebuffers[0].rgba.length,307200);assert.deepStrictEqual(r.assumptions,[]);
 const first=r.states.findIndex(s=>s.imageEcho&&s.imageEcho.started),done=r.states.findIndex((s,i)=>i>first&&s.imageEcho.duration===0);assert.equal(first,692);assert.equal(done-first,53);assert.equal(done,745);assert.equal(r.states[done].imageEcho.liveMatrices,0);assert(r.states.every(s=>!s.imageEcho||s.imageEcho.liveMatrices<=3));assert.equal(r.states[692].actors.length,0);
 assert.equal(r.states[745].effects.filter(e=>e.payload.nativeOpcode==='0x63').length,9);assert(r.states[745].effects.every(e=>e.payload.renderPassSelector===1));
 assert(r.states.some(s=>s.dialogue.some(d=>d.payload.nativeDialogue&&d.payload.nativeDialogue.text.includes('liberate Castle Burgund'))));assert.equal(r.states.at(-1).dialogue.length,0);
 const source=await OB64.cutsceneCodec.loadSceneSource(z64,scene),p=OB64.cutsceneCodec.projectSceneDocument(scene,source,state.catalog),images={};
 for(const pass of [691,712,745,712,691,745]){const target=await OB64.cutsceneUI.capturePreviewFrame(rom,state,p.document,{preview:OB64.cutsceneRuntime.evaluate(r,pass),pass,nodeId:'echo-seek',backgroundPolicy:'omit'});assert(!target.error);if(images[pass])assert.deepStrictEqual(target.rgba,images[pass]);else images[pass]=target.rgba;}
 assert.notDeepStrictEqual(images[691],images[712]);assert.notDeepStrictEqual(images[712],images[745]);
 const again=OB64.cutsceneRuntime.compile(p.document,p.program,scene,state.catalog,{z64,nativeLaunchInputs:input,diagnosticAssumptions:false,maxTicks:1500,captureFrame:()=>({width:320,height:240,rgba:r.framebuffers[0].rgba,targetId:r.framebuffers[0].targetId})});assert.deepStrictEqual(again.states,r.states);assert.notStrictEqual(again.framebuffers[0].rgba,r.framebuffers[0].rgba);
 const controller=new AbortController();await assert.rejects(OB64.cutsceneRuntime.compileAsync(p.document,p.program,scene,state.catalog,{z64,nativeLaunchInputs:input,diagnosticAssumptions:false,maxTicks:1500,signal:controller.signal,captureFrame:async()=>{controller.abort();return {width:320,height:240,rgba:r.framebuffers[0].rgba,targetId:'cancelled'};}}),e=>e.name==='AbortError');
 const invalid=structuredClone(input);invalid.externalProducers.value.imageEcho.kind='recorded-echo';assert.throws(()=>OB64.cutsceneRuntime.compile(p.document,p.program,scene,state.catalog,{z64,nativeLaunchInputs:invalid}),e=>e.code==='image-echo-input');
 console.log(JSON.stringify({status:'pass',states:r.states.length,completedPasses:1434,echoStart:first,echoComplete:done,echoUpdates:53,remaining:r.unresolvedQuery.code,nextConstructor:'node:01F4558C:w03C6',inputBytes:Buffer.byteLength(before)+1,retainedStateBytes:r.retainedStateBytes,defaultUiRoute:true,seekRendering:true,recompileParity:true,cancellation:true,recordedEchoOutcomes:0}));
})().catch(e=>{console.error(e.stack||e);process.exitCode=1;});
