'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert'),R=path.resolve(__dirname,'../..'),fixture=require('./fixtures/cutscene-director-launch.json');
global.window=global;vm.runInThisContext('var OB64=window.OB64={};');
for(const f of ['data.js','parsers.js','art.js','animation-corpus-data.js','animation-art.js','cutscene-data.js','cutscene-model.js','cutscene-catalog.js','cutscene-director.js','cutscene-codec.js','cutscene-dialogue-data.js','cutscene-dialogue-lifecycle-data.js','cutscene-dialogue.js','cutscene-dialogue-lifecycle.js','cutscene-resource-scheduler-data.js','cutscene-resource-scheduler.js','cutscene-director-launch-data.js','cutscene-director-launch.js','cutscene-runtime.js','cutscene-preview.js','cutscene-assets.js','cutscene-sprites.js','cutscene-renderer.js'])vm.runInThisContext(fs.readFileSync(path.join(R,'editor',f),'utf8'),{filename:f});
const v=fs.readFileSync(path.join(R,'Ogre Battle 64 - Person of Lordly Caliber (U) [!].v64')),rom=new Uint8Array(v.length);for(let i=0;i<v.length;i+=2){rom[i]=v[i+1];rom[i+1]=v[i];}
const drain=g=>{let r;do{r=g.next();}while(!r.done);return r.value;},clone=structuredClone,config=fixture.input.externalProducers.value.directorLaunch;
function launch(c=clone(config),image=rom){return new OB64.cutsceneDirectorLaunch(c,image);}
function engine(){return new OB64.cutsceneDialogue.Engine(clone(fixture.input.externalProducers.value.initialDialogue),rom);}
const e=engine(),record=Uint8Array.from({length:168},(_,i)=>e.machine.get(0x800e82c8+i,1)),l=launch();drain(l.initialize(record));const prefix=l.snapshot();
for(const k of ['rootHex','recordHex','contextHex','cameraHex'])assert.equal(prefix[k],fixture.prefix[k],k);
assert.equal(prefix.streamAddress,fixture.prefix.stream);
for(const row of fixture.variants){const c=clone(config);c.selector=row.selector;Object.assign(c.world,Object.fromEntries(['mapKind','scenarioByte','eventState','red','green','blue'].map((k,i)=>[k,row.world[i]])));const x=launch(c);drain(x.initialize(record));const s=x.snapshot();for(const k of ['rootHex','cameraHex','contextHex'])assert.equal(s[k],row[k],row.name+' '+k);assert.deepStrictEqual(Array.from({length:12},(_,i)=>x.machine.get(s.streamAddress+4*i)),row.firstWords);}
for(const row of fixture.audio){const x=launch({...clone(config),audioQueueHex:row.initial}),eng=engine();x.attachResources(eng);for(let i=0;i<row.args.length;i++){const result=drain(eng.machine.run(0x800ea9bc,row.args[i],[]));assert.equal(result,row.outputs[i].result);assert.equal(Buffer.from(x.readEngine(0x800eb8f0,128)).toString('hex'),row.outputs[i].queueHex);}}
for(const mut of [c=>c.sceneMode=2,c=>c.selector=9999,c=>c.world.eventState=-1,c=>c.arena.byteLength=65537,c=>c.cameraBaseHex='00',c=>c.actorPresentationWord=-1]){const c=clone(config);mut(c);assert.throws(()=>launch(c));}
const badRom=rom.slice();badRom[0x2819ec]^=1;assert.throws(()=>launch(clone(config),badRom),e=>e.code==='director-launch-image');
const tiny=launch({...clone(config),arena:{address:0x80360000,byteLength:16}});assert.throws(()=>drain(tiny.initialize(record)),e=>e.code==='director-launch-exhaustion');
const overlap=launch({...clone(config),arena:{address:0x80380000,byteLength:4096}});assert.throws(()=>overlap.attachResources(engine()),e=>e.code==='director-launch-memory');
assert.throws(()=>l.resource(0x100000000),e=>e.code==='director-launch-resource');
const changedCallback=Object.create(OB64.cutsceneResourceScheduler.Scheduler.prototype);changedCallback.engine={owners:[]};changedCallback.read=()=>({initialize:0x8022643c,callback:0x12345678});changedCallback.colorService=function*(){throw new Error('wrong callback executed');};assert.throws(()=>drain(changedCallback.dialogue(1,'callback')),e=>e.code==='dialogue-scheduler-callback');
// Native registration, initialization, callbacks, and release use the same pool.
(function(){
const input=fixture.input,initial=structuredClone(input.externalProducers.value.initialDialogue),e=new OB64.cutsceneDialogue.Engine(initial,rom),launch=new OB64.cutsceneDirectorLaunch(input.externalProducers.value.directorLaunch,rom),drain=g=>{let r;do{r=g.next();}while(!r.done);return r.value;},hex=(a,n)=>Buffer.from(Array.from({length:n},(_,i)=>e.machine.get(a+i,1))).toString('hex');
const m=e.machine,POOL=0x800e82c8,RECORD=0x800e7a30,PAYLOAD=0x800e91d0;drain(launch.initialize(Uint8Array.from(Buffer.from(hex(POOL,168),'hex'))));launch.attachResources(e);const prefix=launch.snapshot();Buffer.from(prefix.recordHex,'hex').forEach((b,i)=>m.put(RECORD+i,b,1));m.put(RECORD,m.get(RECORD,2)|0x2000,2);for(let i=0;i<92;i++)m.put(PAYLOAD+i,0,1);m.put(RECORD+0x24,e.payloadStorage.save(e.owners[0].ownerId,m.get(RECORD+1,1),PAYLOAD,92));e.copy(RECORD,POOL,168);e.owners[0].payload=new Uint8Array(92);m.put(0x800c4c20,0);launch.createColor([27,30,12,34,56,255,0]);
const native=fixture.color;assert.equal(hex(POOL+168,168),native.created,'registered color record');
const schedule={...structuredClone(input.externalProducers.value.resourceSchedule),helperOutcomes:[],controller:{throughPass:15,changes:[{pass:0,actionMask:0,directionMask:0,historyMask:0,dummyMask:0}]}},s=new OB64.cutsceneResourceScheduler.Scheduler(e,schedule,rom);
s.colorService=function*(slot,kind){yield*e.service({service:kind,slot,ownerId:e.owners[slot].ownerId,eligible:true,helpers:[],controller:{...s.control,queueHead:m.get(0x800c4c10,2)}},true,{initialize:0x8022643c,callback:0x80226538,length:92});};
s.beforeDirector=function*(){e.copy(POOL,RECORD,168);e.payloadStorage.restore(e.owners[0].ownerId,m.get(POOL+0x24),PAYLOAD);};s.afterDirector=function*(){m.put(RECORD+0x24,e.payloadStorage.save(e.owners[0].ownerId,m.get(RECORD+1,1),PAYLOAD,92));e.copy(RECORD,POOL,168);};
for(const r of native.updates){if(r.tick===10)launch.releaseColor();drain(s.before(r.tick));drain(s.after(false));assert.equal(hex(POOL+168,168),r.recordHex,'record '+r.tick);assert.equal(e.owners[1]?Buffer.from(e.owners[1].payload).toString('hex'):null,r.payloadHex,'payload '+r.tick);const a=m.get(0x8018fc10);assert.equal(a?hex(a,12):null,r.colorHex,'color '+r.tick);}
})();
(async()=>{const catalog=OB64.cutsceneCatalog.createCatalog(OB64.cutsceneData),scene=catalog.getScene(fixture.input.assetId),source=await OB64.cutsceneCodec.loadSceneSource(rom,scene),p=OB64.cutsceneCodec.projectSceneDocument(scene,source,catalog),run=(input=fixture.input,extra={})=>OB64.cutsceneRuntime.compile(p.document,p.program,scene,catalog,{z64:rom,nativeLaunchInputs:input,diagnosticAssumptions:false,maxTicks:1000,...extra});
const before=JSON.stringify(fixture.input),r=run();assert.equal(JSON.stringify(fixture.input),before);assert(Buffer.byteLength(before)<=131072);assert.equal(r.outcome,'external-input');assert.equal(r.unresolvedQuery.code,'director-launch-iris');assert.equal(r.states.length,642);assert.deepStrictEqual(r.assumptions,[]);
for(const a of fixture.constructors)assert.equal(r.trace.find(t=>t.kind==='direct-actor-creation'&&t.slot===a.words[1]).recordHex,a.recordHex,'complete native constructor '+a.words[1]);
assert.equal(r.directorInitialization.initialParser.cameraHex,fixture.startup.cameraHex);assert(r.trace.some(t=>t.kind==='parser-resume-commit'&&t.tick===0&&t.destinationWord===fixture.startup.parserWord));
for(const a of fixture.startup.actors){const b=Buffer.from(a.recordHex,'hex'),values=[...Array.from({length:3},(_,i)=>b.readFloatBE(0x11c+4*i)),...Array.from({length:4},(_,i)=>b.readInt32BE(i?0xec+4*i:0xe8)),b.readInt16BE(0x134),b.readInt16BE(0x138),b[0x13f]];assert.deepStrictEqual(r.directorInitialization.initialParser.actors.find(x=>x.slot===a.slot).values,values);}
const unknown=clone(fixture.input);unknown.externalProducers={status:"unknown"};assert.doesNotThrow(()=>run(unknown));
const stale=clone(fixture.input);stale.externalProducers.value.directorLaunch.selector=1;assert.equal(run(stale).unresolvedQuery.code,'director-launch-selector');
const noAudio=clone(fixture.input);delete noAudio.externalProducers.value.directorLaunch.audioQueueHex;assert.equal(run(noAudio).unresolvedQuery.code,'dialogue-helper-outcome');
const neutral=clone(fixture.input);neutral.externalProducers.value.resourceSchedule.controller.changes=[{pass:0,actionMask:0,directionMask:0,historyMask:0,dummyMask:0}];const nr=run(neutral,{maxTicks:120});assert.equal(nr.outcome,'tick-limit');assert(nr.states.at(-1).dialogue.length);
const sprites=OB64.cutsceneSprites.create(rom,catalog);let rendered=0,actorFrames=0,audioEvents=0,effectFrames=0;
for(const s of r.states){const frames=OB64.cutsceneSprites.framesForPreview(sprites,s);assert.equal(Object.keys(frames).length,s.actors.length);actorFrames+=s.actors.length;audioEvents+=s.audio.filter(x=>x.kind==='native-audio-request').length;const effects=s.effects.filter(row=>row.payload.sourceSystem==='cutscene-sprite-native'&&!row.payload.nativeLifetimeEmpty).map(row=>{const a=row.payload,image=OB64.cutsceneSprites.frameForActor(sprites,{poseId:a.poseId,bank:a.bank,animationKey:a.animationKey,nativeFacing:a.nativeFacing,variantSelector:a.variantSelector,poseFrame:a.poseFrame,poseLoop:a.poseLoop,displayedFrameToken:a.displayedFrameToken});assert(image);effectFrames++;return {image,x:a.stageX,y:a.stageY,scale:a.scale,rotationDegrees:a.rotationDegrees||0,anchorX:image.anchorX,anchorY:image.anchorY};});const image=OB64.cutsceneRenderer.renderFrame(p.document,s,{actorFrames:frames,effectFrames:effects,backgrounds:[],overlays:s.overlays||[],projection:s.actorProjection,camera:s.cameraState,colorModulation:s.sceneColor});assert.equal(image.rgba.length,320*240*4);rendered++;}
assert.deepStrictEqual(sprites.errors,{});assert(audioEvents>0);const asyncResult=await OB64.cutsceneRuntime.compileAsync(p.document,p.program,scene,catalog,{z64:rom,nativeLaunchInputs:fixture.input,diagnosticAssumptions:false,maxTicks:1000});assert.deepStrictEqual(asyncResult.states,r.states);
console.log(JSON.stringify({status:'pass',launchVariants:fixture.variants.length,nativeConstructorRecords:fixture.constructors.length,nativeInitialParserActors:fixture.startup.actors.length,resourcePassStates:r.states.length,completedPasses:r.states.length-1,rendered,actorFrames,effectFrames,audioEvents,audioQueueControls:fixture.audio.length,colorNativePasses:fixture.color.updates.length,inputBytes:Buffer.byteLength(before),remaining:r.unresolvedQuery,neutral120:true,asyncParity:true,rendering:'Actor renderer and computed overlays; backgrounds omitted; no pixel or rendered-frame timing claim'}));
})().catch(e=>{console.error(e.stack||e);process.exitCode=1;});
