'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert'),R=path.resolve(__dirname,'../..');
global.window=global;vm.runInThisContext('var OB64=window.OB64={};');
for(const f of ['data.js','parsers.js','art.js','animation-corpus-data.js','animation-art.js','cutscene-data.js','cutscene-model.js','cutscene-catalog.js','cutscene-director.js','cutscene-codec.js','cutscene-dialogue-data.js','cutscene-dialogue-lifecycle-data.js','cutscene-dialogue.js','cutscene-dialogue-lifecycle.js','cutscene-resource-scheduler-data.js','cutscene-resource-scheduler.js','cutscene-director-launch-data.js','cutscene-director-launch.js','cutscene-runtime.js','cutscene-preview.js','cutscene-assets.js','cutscene-sprites.js','cutscene-renderer.js','cutscene-dialogue-draw.js','rom-compatibility.js','cutscene-framebuffer-data.js','cutscene-framebuffer.js','cutscene-ui.js'])vm.runInThisContext(fs.readFileSync(path.join(R,'editor',f),'utf8'),{filename:f});
(async()=>{const v=fs.readFileSync(path.join(R,'Ogre Battle 64 - Person of Lordly Caliber (U) [!].v64')),z64=new Uint8Array(v.length);for(let i=0;i<v.length;i+=2){z64[i]=v[i+1];z64[i+1]=v[i];}const input=structuredClone(require('./fixtures/cutscene-director-launch.json').input);input.invocationId='framebuffer-effects-20260916';input.externalProducers.value.framebuffer={kind:'product-framebuffer-v1',capturePolicy:'constructor-current-state',backgroundPolicy:'omit'};
const catalog=OB64.cutsceneCatalog.createCatalog(OB64.cutsceneData),scene=catalog.getScene(input.assetId),source=await OB64.cutsceneCodec.loadSceneSource(z64,scene),p=OB64.cutsceneCodec.projectSceneDocument(scene,source,catalog),rom={z64,archives:OB64.findArchives(z64)},state={catalog,spriteState:OB64.cutsceneSprites.create(z64,catalog),imageCache:{},imageLoading:{},imageClock:0,imageCacheBytes:0,combatEffectCache:{},sourceErrors:{}};

const options={z64,nativeLaunchInputs:input,diagnosticAssumptions:false,maxTicks:1000};
const run=(captureFrame,extra={})=>OB64.cutsceneRuntime.compile(p.document,p.program,scene,catalog,{...options,captureFrame,...extra});
let currentTarget,captures=0;const before=JSON.stringify(input);
const r=await OB64.cutsceneRuntime.compileAsync(p.document,p.program,scene,catalog,{...options,captureFrame:async request=>{captures++;assert.equal(request.pass,641);assert.equal(request.nodeId,'node:01F4558C:w016D');assert.equal(request.preview.actors.length,7);currentTarget=await OB64.cutsceneUI.capturePreviewFrame(rom,state,p.document,request);assert.deepStrictEqual(currentTarget.movementPaths,[]);return currentTarget;}});
assert.equal(JSON.stringify(input),before);assert(Buffer.byteLength(before)<131072);assert.equal(captures,1);assert.equal(r.states.length,693);assert.equal(r.unresolvedQuery.code,'framebuffer-echo');assert.deepStrictEqual(r.assumptions,[]);assert.equal(r.framebuffers.length,1);assert.equal(r.framebuffers[0].rgba.length,307200);
assert.equal(r.states[641].framebufferEffect.record.progress,0);assert.equal(r.states[641].sceneVignette.activeSlotByte,6);assert.equal(r.states[691].framebufferEffect.record.progress,50);assert.equal(r.states[692].framebufferEffect.record.progress,51);assert.equal(r.states[692].actors.length,0);assert(!r.states[692].effects.some(e=>e.payload.sourceSystem==='cutscene-sprite-native'&&!e.payload.nativeLifetimeEmpty));
for(let i=0;i<307200;i++){assert.equal(r.framebuffers[0].rgba[i],i%4===3?255:Math.round((currentTarget.rgba[i]>>>3)*255/31));}
const sync=run(()=>currentTarget);assert.deepStrictEqual(sync.states,r.states);assert.deepStrictEqual(sync.framebuffers,r.framebuffers);assert.notStrictEqual(sync.framebuffers[0].rgba,r.framebuffers[0].rgba);
const savedFirst=r.framebuffers[0].rgba[0];currentTarget.rgba[0]^=255;assert.equal(r.framebuffers[0].rgba[0],savedFirst);currentTarget.rgba[0]^=255;
const pixels={};for(const pass of [640,666,692,641,666,692,640]){const view=OB64.cutsceneRuntime.evaluate(r,pass);const image=await OB64.cutsceneUI.capturePreviewFrame(rom,state,p.document,{preview:view,pass,nodeId:'seek',backgroundPolicy:'omit'});if(pixels[pass])assert.deepStrictEqual(image.rgba,pixels[pass]);else pixels[pass]=image.rgba;}
assert.notDeepStrictEqual(pixels[640],pixels[666]);assert.notDeepStrictEqual(pixels[666],pixels[692]);
for(const target of [null,{...currentTarget,targetId:''},{...currentTarget,width:319},{...currentTarget,rgba:new Uint8ClampedArray(307200)},{error:'deliberate renderer failure'}]){const fail=run(()=>target);assert.equal(fail.unresolvedQuery.code,'framebuffer-target');assert.equal(fail.framebuffers.length,0);}
const promised=run(()=>Promise.resolve(currentTarget));assert.equal(promised.unresolvedQuery.code,'framebuffer-target');const rejected=run(()=>Promise.reject(new Error('unsupported async service')));assert.equal(rejected.unresolvedQuery.code,'framebuffer-target');await Promise.resolve();
const controller=new AbortController();await assert.rejects(OB64.cutsceneRuntime.compileAsync(p.document,p.program,scene,catalog,{...options,signal:controller.signal,captureFrame:async()=>{controller.abort();return currentTarget;}}),e=>e.name==='AbortError');
let release,entered;const pending=new Promise(resolve=>entered=resolve),abort=new AbortController(),cancelRun=OB64.cutsceneRuntime.compileAsync(p.document,p.program,scene,catalog,{...options,signal:abort.signal,captureFrame:()=>{entered();return new Promise(resolve=>release=resolve);}});await pending;abort.abort();await assert.rejects(cancelRun,e=>e.name==='AbortError');release(currentTarget);
// This edited prefix is a lifecycle control, not the unmodified retail continuation.
const close=p.ir.nodes.find(n=>n.definition.name==='frozen_frame_iris_transition'&&n.rawWords[8]===0),open=p.ir.nodes.find(n=>n.definition.name==='frozen_frame_iris_transition'&&n.rawWords[8]===1),gate=p.ir.nodes.filter(n=>n.definition.startWord>=0x17b&&n.definition.startWord<0x181);
function edited(cycles=1,duration=3){const prefix=p.ir.nodes.filter(n=>n.definition.startWord<0x16d),nodes=prefix.concat(Array.from({length:cycles},()=>[close,...gate,open,...gate]).flat(),p.ir.nodes.slice(-1));let cursor=0;const words=[],definitions=nodes.map(n=>{const w=n.rawWords.slice();if(n.definition.name==='frozen_frame_iris_transition'){w[1]=180;w[2]=100;w[3]=27;w[4]=-18;w[6]=128;w[7]=duration;}words.push(...w);const d={...n.definition,startWord:cursor,endWord:cursor+w.length,id:'node:01F4558C:w'+cursor.toString(16).toUpperCase().padStart(4,'0')};cursor=d.endWord;return d;}),editedScene=structuredClone(scene);Object.assign(editedScene.source,{decodedLength:cursor*4,decodedWordCount:cursor,runtimeNodeCount:nodes.length});return {scene:editedScene,...OB64.cutsceneCodec.projectSceneDocument(editedScene,{decodedBytes:OB64.cutsceneCodec.wordsToBytes(words),nodeDefinitions:definitions},catalog)};}
const ep=edited(),solid={width:320,height:240,targetId:'declared-blue-control',rgba:Uint8ClampedArray.from({length:307200},(_,i)=>i%4>=2?255:0)},er=OB64.cutsceneRuntime.compile(ep.document,ep.program,ep.scene,catalog,{...options,captureFrame:()=>solid});assert.equal(er.outcome,'modeled-termination');assert.equal(er.states.at(-1).framebufferEffect.record,null);assert.equal(er.states.at(-1).framebufferEffect.imageId,null);assert.equal(er.states.at(-1).framebufferEffect.selected,2);assert.equal(er.states.at(-1).sceneVignette.activeSlotByte,2);assert.equal(er.framebuffers.length,1);assert(!er.states.at(-1).actors.length);assert.deepStrictEqual(er.framebuffers[0].rgba,solid.rgba);assert.notDeepStrictEqual(er.framebuffers[0].rgba,r.framebuffers[0].rgba);assert.equal(er.states[641].framebufferEffect.record.radiusX,180);
const many=edited(9,1),mr=OB64.cutsceneRuntime.compile(many.document,many.program,many.scene,catalog,{...options,captureFrame:()=>solid});assert.equal(mr.unresolvedQuery.code,'framebuffer-storage-limit');assert.equal(mr.framebuffers.length,8);assert.equal(mr.framebuffers.reduce((n,f)=>n+f.rgba.length,0),2457600);
const bad=structuredClone(input);bad.externalProducers.value.framebuffer.capturePolicy='last-displayed-frame';assert.throws(()=>run(()=>solid,{nativeLaunchInputs:bad}),e=>e.code==='framebuffer-input');const corrupt=z64.slice();corrupt[0x2b64ac]^=1;assert.throws(()=>run(()=>solid,{z64:corrupt}),e=>e.code==='framebuffer-image');
console.log(JSON.stringify({status:'pass',retailStates:r.states.length,completedPasses:r.states.length-1,capturePass:641,remaining:r.unresolvedQuery.code,editedPairedPhases:er.outcome,editedStates:er.states.length,retentionBound:mr.framebuffers.length,cancellationControls:2,seekRenderPasses:7,syncAsyncParity:true,inputBytes:Buffer.byteLength(before)}));
})().catch(e=>{console.error(e.stack||e);process.exitCode=1;});
