const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert'),O=__dirname,R=path.resolve(O,'../..');global.window=global;global.OB64={};vm.runInThisContext(fs.readFileSync(path.join(R,'editor/cutscene-framebuffer.js'),'utf8'));const f=require('./fixtures/cutscene-framebuffer.json'),hex=b=>Buffer.from(b).toString('hex');
for(const c of f.cases){const layers=Array.from({length:20},(_,i)=>({resource:0x10000000+i,record:Uint8Array.from({length:88},(_,j)=>(i*7+j)&255)})),iris=new OB64.cutsceneFramebuffer.Iris(c.count,c.selected,layers),actors=c.layers.map(layer=>({layer})),effects=c.layers.map(layer=>({layer}));let closed=false;
for(const n of c.states){if(n.tag==='close-create')iris.create(c.args,'image',actors,effects);else if(n.tag==='open-create'){const args=c.args.slice();args[7]=1;iris.create(args,null,actors,effects);}else if(iris.advance())closed=true;
assert.equal(iris.recordBytes()?hex(iris.recordBytes()):null,n.recordHex,n.tag);assert.equal(iris.query(),n.query);assert.equal(iris.selected,n.layerIndex);assert.equal(hex(Buffer.concat(iris.layers.map(r=>Buffer.from(r.record)))),n.recordsHex,n.tag+' records');assert.deepStrictEqual(actors.map(a=>closed?null:a.layer),n.actors);assert.deepStrictEqual(effects.map(a=>closed?null:a.layer),n.effects);assert.equal(!!iris.imageId,n.framePresent);for(let i=0;i<20;i++){const r=iris.layers[i].resource;if(typeof r==='number'||r===null)assert.equal(r||0,n.layerResources[i]);}}
}
let maxError=0;for(const m of f.meshes){const b=Buffer.from(m.vertexHex,'hex'),v=OB64.cutsceneFramebuffer.mesh({radiusX:m.args[0],radiusY:m.args[1],centerX:m.args[2],centerY:m.args[3],alpha:m.args[4]});assert.equal(v.length,m.vertices);const computed=Buffer.alloc(v.length*16);v.forEach((p,i)=>{computed.writeInt16BE(p[0],i*16);computed.writeInt16BE(p[1],i*16+2);computed[i*16+15]=p[2];});assert.deepStrictEqual(computed,b);v.forEach((p,i)=>{maxError=Math.max(maxError,Math.abs(p[0]-b.readInt16BE(i*16)),Math.abs(p[1]-b.readInt16BE(i*16+2)));assert.equal(p[2],b[i*16+15]);});}assert.equal(maxError,0);const report={status:'pass',nativeLifecycleSnapshots:28,nativeFrameCopies:2,nativeMeshes:f.meshes.length,maxVertexDifference:maxError};console.log(report);

const F=OB64.cutsceneFramebuffer,layers=()=>Array.from({length:20},()=>({resource:null,record:new Uint8Array(88)})),make=()=>new F.Iris(7,2,layers()),args=[320,240,-110,44,0,200,3,0,1];
for(const index of [0,1,2,3,5,6,7]){const bad=args.slice();bad[index]=index===5?256:index===6?0:index===7?2:32767;assert.throws(()=>make().create(bad,0,[],[]));}
assert.throws(()=>make().create(args,null,[],[]));assert.throws(()=>make().create([...args.slice(0,7),1,1],null,[],[]));
assert.throws(()=>new F.Iris(21,2,layers()));assert.throws(()=>new F.Iris(7,7,layers()));
const iris=make(),actors=[{layer:1},{layer:2},{layer:3}],effects=[{layer:1},{layer:2},{layer:3}];iris.create(args,0,actors,effects);assert.deepStrictEqual(actors.map(x=>x.layer),[1,1,2]);assert.deepStrictEqual(effects.map(x=>x.layer),[1,2,2]);assert.throws(()=>iris.create(args,1,[],[]));
new DataView(iris.layers[3].record.buffer).setFloat32(72,123.5);while(iris.query())iris.advance();assert.equal(new DataView(iris.saved[3].record.buffer).getFloat32(72),123.5);iris.create([...args.slice(0,7),1,1],null,[],[]);assert.equal(new DataView(iris.layers[3].record.buffer).getFloat32(72),123.5);while(iris.query())iris.advance();assert.equal(iris.record,null);assert.equal(iris.imageId,null);assert.equal(iris.saved,null);
console.log('PASS: phase/layer/bounds controls and current transform preservation');
