const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert'),R=path.resolve(__dirname,'../..');global.window=global;global.OB64={};
for(const f of ['cutscene-codec.js','cutscene-dialogue.js','cutscene-director-launch.js','cutscene-image-echo.js','cutscene-map-menu-data.js','cutscene-map-menu.js'])vm.runInThisContext(fs.readFileSync(path.join(R,'editor',f),'utf8'),{filename:f});
const v=fs.readFileSync(path.join(R,'Ogre Battle 64 - Person of Lordly Caliber (U) [!].v64')),rom=new Uint8Array(v.length);for(let i=0;i<v.length;i+=2){rom[i]=v[i+1];rom[i+1]=v[i];}
for(const row of require('./fixtures/cutscene-map-menu.json').cases){const m=new OB64.cutsceneMapMenu(rom,{kind:'native-map-menu-v1',initialEntitiesEmpty:true,displayMode:0});m.create(4,33,row.width,row.height);for(let i=0;i<row.states.length;i++){if(i===row.states.length-1)m.release(4);else if(i)m.advance(i-1===row.press?row.mask:0);const s=m.snapshot(),n=row.states[i];assert.equal(m.query(4),n.query|0,'query '+i);assert.equal(m.query(5),-5);if(s.entities.length){const e=s.entities[0],a=Buffer.from(e.recordHex,'hex'),b=Buffer.from(n.entityHex,'hex');for(const offset of [0,4,0xd0]){a.fill(0,offset,offset+4);b.fill(0,offset,offset+4);}assert.equal(a.toString('hex'),b.toString('hex'),'entity '+i);const pa=Buffer.from(e.payloadHex,'hex'),pb=Buffer.from(n.payloadHex,'hex');for(let o=0x530;o<0x5f0;o+=4){if(pa.readUInt32BE(o))pa.writeUInt32BE(pa.readUInt32BE(o)-e.payload,o);if(pb.readUInt32BE(o))pb.writeUInt32BE(pb.readUInt32BE(o)-n.payload,o);}assert.equal(pa.toString('hex'),pb.toString('hex'),'payload '+i);}assert.equal(!!s.entities.length,n.attached,'attached '+i);}console.log('native exact',row.width,row.height,row.mask,row.press);}

for(const row of require('./fixtures/cutscene-map-menu.json').draw){const m=new OB64.cutsceneMapMenu(rom,{kind:'native-map-menu-v1',initialEntitiesEmpty:true,displayMode:0});m.create(4,33,row.width,row.height);for(let i=0;i<row.updates;i++)m.advance(0);assert.deepStrictEqual(OB64.cutsceneMapMenu.lines(m.snapshot().entities[0]),row.text);}
console.log('native text calls exact: six alpha/geometry/layout states');

const profile={kind:'native-map-menu-v1',initialEntitiesEmpty:true,displayMode:0};
for(const at of [0x2a6150,0x5a0f4,0x52484,0x66da0,0x2a8c00]){const bad=rom.slice();bad[at]^=1;assert.throws(()=>new OB64.cutsceneMapMenu(bad,profile),e=>e.code==='map-menu-image');}
const menu=new OB64.cutsceneMapMenu(rom,profile);assert.equal(menu.query(4),-5);assert.throws(()=>menu.create(4,3,240,144),e=>e.code==='map-menu-input');assert.equal(menu.snapshot().entities.length,0);
for(const slot of [-1,14,1.5])assert.throws(()=>menu.query(slot),e=>e.code==='map-menu-input');
menu.create(4,33,240,144);const saved=structuredClone(menu.snapshot());for(let i=0;i<14;i++)menu.advance(0);assert.equal(saved.entities[0].alpha,0);assert.equal(menu.snapshot().entities[0].alpha,255);
menu.advance(32768);assert.equal(menu.query(4),0);for(let i=0;i<14;i++)menu.advance(0);assert.equal(menu.query(4),-6);assert.equal(menu.snapshot().entities.length,0);assert.equal(menu.leases.length,1);menu.release(-1);assert.equal(menu.query(4),-5);assert.equal(menu.leases.length,0);
const reserved=menu.allocate(8192);assert.throws(()=>menu.create(4,33,240,144),e=>e.code==='map-menu-exhaustion');assert.equal(menu.query(4),-5);menu.machine.r[4]=reserved;menu.helper(0x800712c4);assert.throws(()=>menu.helper(0x800712c4),e=>e.code==='map-menu-owner');
assert.throws(()=>menu.machine.put(0x80395000,1),e=>e.code==='dialogue-reached-memory');assert.throws(()=>new OB64.cutsceneMapMenu(rom,{...profile,initialEntitiesEmpty:false}),e=>e.code==='map-menu-input');
console.log(JSON.stringify({status:'pass',nativeLifecycleStates:168,nativeDrawStates:6,romGuards:true,absentDetachedReleased:true,bounds:true,readinessComputed:true}));
