'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert'),R=path.resolve(__dirname,'../..');
const boot=fs.readFileSync(path.join(__dirname,'cutscene-framebuffer-integration.test.js'),'utf8').split('(async()=>')[0];new Function('require','__dirname',boot)(require,__dirname);
for(const f of ['cutscene-image-echo-data.js','cutscene-image-echo.js','cutscene-map-menu-data.js','cutscene-map-menu.js'])vm.runInThisContext(fs.readFileSync(path.join(R,'editor',f),'utf8'),{filename:f});
(async()=>{
 const v=fs.readFileSync(path.join(R,'Ogre Battle 64 - Person of Lordly Caliber (U) [!].v64')),z64=new Uint8Array(v.length);for(let i=0;i<v.length;i+=2){z64[i]=v[i+1];z64[i+1]=v[i];}
 const rom={z64,archives:OB64.findArchives(z64),layout:{id:'us-rev0'}},state=OB64.cutsceneUI.initialize(rom),input=structuredClone(require('./fixtures/cutscene-map-option-menu.json').input),before=JSON.stringify(input),scene=state.catalog.getScene(input.assetId);
 assert(Buffer.byteLength(before)<131072);assert.equal(OB64.cutsceneUI.launchContextChoice(state,scene,null).id,'event-director:7:b00A4:invocation:52:context:0');
 OB64.cutsceneUI.setNativeLaunchInputs(state,scene,input);await OB64.cutsceneUI.loadScene(rom,state,scene);const r=state.runtimeByAssetId[scene.assetId];
 assert.equal(JSON.stringify(input),before);assert.equal(r.states.length,2307,JSON.stringify(r.unresolvedQuery));assert.equal(r.unresolvedQuery,null);assert.equal(r.outcome,'shared-pose-control-18');assert.equal(r.states.at(-1).runtime.status,'missing-inputs');assert(r.states.at(-1).actors.some(a=>a.slot===3&&a.poseBlocked==='shared-pose-control-18'));assert.equal(r.trace.filter(t=>t.kind==='resource-pass').length,2306);assert.equal(r.trace.at(-1).nodeId,'node:01F4558C:w0620');assert.equal(r.states.at(-1).mapMenu.entities.length,0);assert.equal(r.states[1500].mapMenu.entities[0].selection,1);assert.equal(r.states[1530].mapMenu.owners[0].status,1);assert.equal(r.states[1560].mapMenu.owners[0].status,0);assert.equal(r.states[1572].mapMenu.owners[0].status,-6);assert(r.trace.some(t=>t.kind==='branch-query'&&t.nodeId==='node:01F4558C:w0465'&&t.actual===-1&&t.passed));assert(r.trace.find(t=>t.kind==='map-menu-memory').bytes<=131072);assert.equal(r.states[1470].mapMenu.owners[4].status,0);assert.equal(r.states[1482].mapMenu.owners[4].status,-6);assert(r.framebuffers.length>=1);assert.equal(r.framebuffers[0].pass,641);assert.equal(r.framebuffers[0].rgba.length,307200);assert.deepStrictEqual(r.assumptions,[]);
 const first=r.states.findIndex(s=>s.imageEcho&&s.imageEcho.started),done=r.states.findIndex((s,i)=>i>first&&s.imageEcho.duration===0);assert.equal(first,692);assert.equal(done-first,53);assert.equal(done,745);assert.equal(r.states[done].imageEcho.liveMatrices,0);assert(r.states.every(s=>!s.imageEcho||s.imageEcho.liveMatrices<=3));assert.equal(r.states[692].actors.length,0);
 assert.equal(r.states[745].effects.filter(e=>e.payload.nativeOpcode==='0x63').length,9);assert(r.states[745].effects.every(e=>e.payload.renderPassSelector===1));
 assert(r.states.some(s=>s.dialogue.some(d=>d.payload.nativeDialogue&&d.payload.nativeDialogue.text.includes('liberate Castle Burgund'))));assert.equal(r.states.at(-1).dialogue.length,0);
 const source=await OB64.cutsceneCodec.loadSceneSource(z64,scene),p=OB64.cutsceneCodec.projectSceneDocument(scene,source,state.catalog),images={};
 for(const pass of [1499,1500,1550,1565,1575,1500,1565]){const target=await OB64.cutsceneUI.capturePreviewFrame(rom,state,p.document,{preview:OB64.cutsceneRuntime.evaluate(r,pass),pass,nodeId:'echo-seek',backgroundPolicy:'omit'});assert(!target.error);if(images[pass])assert.deepStrictEqual(target.rgba,images[pass]);else images[pass]=target.rgba;}
 assert.notDeepStrictEqual(images[1499],images[1500]);assert.notDeepStrictEqual(images[1550],images[1565]);
 const again=OB64.cutsceneRuntime.compile(p.document,p.program,scene,state.catalog,{z64,nativeLaunchInputs:input,diagnosticAssumptions:false,maxTicks:2400,captureFrame:request=>{const f=r.framebuffers.find(x=>x.pass===request.pass);assert(f);return {width:320,height:240,rgba:f.rgba,targetId:f.targetId};}});assert.deepStrictEqual(again.states,r.states);assert.notStrictEqual(again.framebuffers[0].rgba,r.framebuffers[0].rgba);
 const controller=new AbortController();await assert.rejects(OB64.cutsceneRuntime.compileAsync(p.document,p.program,scene,state.catalog,{z64,nativeLaunchInputs:input,diagnosticAssumptions:false,maxTicks:2400,signal:controller.signal,captureFrame:async()=>{controller.abort();return {width:320,height:240,rgba:r.framebuffers[0].rgba,targetId:'cancelled'};}}),e=>e.name==='AbortError');
 const menuAbort=new AbortController(),create=OB64.cutsceneMapMenu.prototype.create;let reachedMenu=false;OB64.cutsceneMapMenu.prototype.create=function(...args){const result=create.apply(this,args);reachedMenu=true;menuAbort.abort();return result;};
 try{await assert.rejects(OB64.cutsceneRuntime.compileAsync(p.document,p.program,scene,state.catalog,{z64,nativeLaunchInputs:input,diagnosticAssumptions:false,maxTicks:2400,signal:menuAbort.signal,captureFrame:()=>({width:320,height:240,rgba:r.framebuffers[0].rgba,targetId:'menu-cancel'})}),e=>e.name==='AbortError');}finally{OB64.cutsceneMapMenu.prototype.create=create;}assert(reachedMenu);
 const recorded=structuredClone(input);recorded.externalProducers.value.events={templates:[{kind:'menu'}],sequence:[]};assert.throws(()=>OB64.cutsceneRuntime.compile(p.document,p.program,scene,state.catalog,{z64,nativeLaunchInputs:recorded}),e=>e.code==='map-menu-input');
 const invalid=structuredClone(input);invalid.externalProducers.value.imageEcho.kind='recorded-echo';assert.throws(()=>OB64.cutsceneRuntime.compile(p.document,p.program,scene,state.catalog,{z64,nativeLaunchInputs:invalid}),e=>e.code==='image-echo-input');
 console.log(JSON.stringify({status:'pass',states:r.states.length,completedPasses:2306,echoStart:first,echoComplete:done,echoUpdates:53,remaining:r.outcome,nextNode:'node:01F4558C:w0620',inputBytes:Buffer.byteLength(before)+1,retainedStateBytes:r.retainedStateBytes,defaultUiRoute:true,seekRendering:true,recompileParity:true,cancellation:true,recordedMenuOutcomes:0,menuCancellation:true,menuDismissedAt:1470,menuDetachedAt:1482}));
})().catch(e=>{console.error(e.stack||e);process.exitCode=1;});
