const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert'),R=path.resolve(__dirname,'../..');global.window=global;global.OB64={};
for(const f of ['cutscene-codec.js','cutscene-dialogue.js','cutscene-director-launch.js','cutscene-image-echo.js','cutscene-map-menu-data.js','cutscene-map-menu.js'])vm.runInThisContext(fs.readFileSync(path.join(R,'editor',f),'utf8'),{filename:f});
const v=fs.readFileSync(path.join(R,'Ogre Battle 64 - Person of Lordly Caliber (U) [!].v64')),rom=new Uint8Array(v.length);for(let i=0;i<v.length;i+=2){rom[i]=v[i+1];rom[i+1]=v[i];}
for(const row of require('./fixtures/cutscene-map-option-menu.json').cases){assert.equal(row.error,null);const m=new OB64.cutsceneMapMenu(rom,{kind:'native-map-menu-v1',initialEntitiesEmpty:true,displayMode:0,optionController:'declared-action-direction-v1'});m.create(4,row.preset||3,row.width,row.height);if(row.replacement)m.create(4,3,row.width,row.height);const audio=[];for(let i=0;i<row.states.length;i++){if(i===row.states.length-1)m.release(4);else if(i)audio.push(...m.advance(i-1===row.press?row.mask:0,row.directions[i-1]||0).map(e=>e.program));const s=m.snapshot(),n=row.states[i];if(n.ownerHex){const a=Buffer.from(s.owners[4].recordHex,'hex'),b=Buffer.from(n.ownerHex,'hex');a.fill(0,12,16);b.fill(0,12,16);assert.equal(a.toString('hex'),b.toString('hex'),'owner '+i);}else assert.equal(s.owners[4],null);assert.equal(m.query(4),n.query|0,'query '+i);assert.equal(m.query(5),-5);if(s.entities.length){const e=s.entities[0],a=Buffer.from(e.recordHex,'hex'),b=Buffer.from(n.entityHex,'hex');for(const offset of [0,4,0xd0]){a.fill(0,offset,offset+4);b.fill(0,offset,offset+4);}assert.equal(a.toString('hex'),b.toString('hex'),'entity '+i);const pa=Buffer.from(e.payloadHex,'hex'),pb=Buffer.from(n.payloadHex,'hex');for(let o=0x530;o<0x5f0;o+=4){if(pa.readUInt32BE(o))pa.writeUInt32BE(pa.readUInt32BE(o)-e.payload,o);if(pb.readUInt32BE(o))pb.writeUInt32BE(pb.readUInt32BE(o)-n.payload,o);}assert.equal(pa.toString('hex'),pb.toString('hex'),'payload '+i);}assert.equal(!!s.entities.length,n.attached,'attached '+i);if(n.entities){assert.equal(s.entities.length,n.entities.length);s.entities.forEach((e,j)=>{const a=Buffer.from(e.recordHex,'hex'),b=Buffer.from(n.entities[j].recordHex,'hex');for(const o of [0,4,0xd0]){a.fill(0,o,o+4);b.fill(0,o,o+4);}assert.equal(a.toString('hex'),b.toString('hex'),'all entities '+i+':'+j);});}}assert.deepStrictEqual(audio,row.audio,'audio requests');console.log('native exact',row.width,row.height,row.mask,row.press);}


for(const row of require('./fixtures/cutscene-map-option-menu.json').draw){const m=new OB64.cutsceneMapMenu(rom,{kind:'native-map-menu-v1',initialEntitiesEmpty:true,displayMode:0,optionController:'declared-action-direction-v1'});m.create(4,row.preset||3,240,144);for(let i=0;i<row.updates;i++)m.advance(i===29?row.action:0,i===20?row.direction:0);const entities=m.snapshot().entities;assert.deepStrictEqual(entities.flatMap(e=>OB64.cutsceneMapMenu.lines(e)),row.text);const cursors=entities.map(e=>OB64.cutsceneMapMenu.cursor(e)).filter(Boolean).map(c=>[c.x,c.y]);assert.deepStrictEqual(cursors,row.helpers.filter(x=>x.cursor).map(x=>x.cursor));}console.log('Nine native text/cursor states pass');

const profile={kind:'native-map-menu-v1',initialEntitiesEmpty:true,displayMode:0,optionController:'declared-action-direction-v1'},m=new OB64.cutsceneMapMenu(rom,profile);assert.throws(()=>m.advance(0),e=>e.code==='map-menu-input');assert.throws(()=>new OB64.cutsceneMapMenu(rom,{...profile,optionController:'unknown'}),e=>e.code==='map-menu-input');for(const at of [0x2a6be4,0x55308,0x55014,0x54b84,0x521fc]){const bad=rom.slice();bad[at]^=1;assert.throws(()=>new OB64.cutsceneMapMenu(bad,profile),e=>e.code==='map-menu-image');}m.create(0,3,320,240);m.create(0,3,320,240);assert.equal(m.snapshot().entities.length,1);assert.equal(m.leases.length,3);console.log('Option bounds, ROM guards, and same-slot replacement pass');
