'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert'),root=path.resolve(__dirname,'../..');
new Function('require','__dirname',fs.readFileSync(path.join(__dirname,'cutscene-shared-rom-start.test.js'),'utf8').split('\n(async()=>')[0])(require,__dirname);
for(const f of ['cutscene-preserved-stage-data.js','cutscene-preserved-stage.js'])vm.runInThisContext(fs.readFileSync(path.join(root,'editor',f),'utf8'),{filename:f});
(async()=>{
 const raw=fs.readFileSync(path.join(root,'Ogre Battle 64 - Person of Lordly Caliber (U) [!].v64')),z64=new Uint8Array(raw.length);for(let i=0;i<raw.length;i+=2){z64[i]=raw[i+1];z64[i+1]=raw[i];}
 const rom={z64,archives:OB64.findArchives(z64),layout:{id:'us-rev0'}},ui=OB64.cutsceneUI.initialize(rom),runs=[],owned=[];
 const Stage=OB64.cutscenePreservedStage;OB64.cutscenePreservedStage=function(...args){const stage=new Stage(...args);owned.push(stage);return stage;};OB64.cutscenePreservedStage.prototype=Stage.prototype;
 const initialize=OB64.cutsceneDirectorLaunch.prototype.initialize,retained=[];
 OB64.cutsceneDirectorLaunch.prototype.initialize=function*(record){const stage=this.stage,before=stage&&stage.rows();yield* initialize.call(this,record);if(stage){assert.equal(this.initializeCallback,0x80226324);assert.equal(this.machine.get(0x8022a981,1),1);assert.equal(this.machine.get(0x801ce8bc),stage.root);assert.deepStrictEqual(stage.rows(),before);assert.deepStrictEqual(this.read(0x80220e70,30),stage.read(0x80220e70,30));retained.push(stage.root);}};
 try{
 for(const [id,count,changedBank]of [['01F450D0',485,13],['01F4C45A',627,10]]){
  const scene=ui.catalog.getScene('rom-director:'+id),source=await OB64.cutsceneCodec.loadSceneSource(z64,scene),p=OB64.cutsceneCodec.projectSceneDocument(scene,source,ui.catalog),input=OB64.cutsceneRomStart.input(z64,scene,p.program);
  assert.equal(input.externalProducers.value.directorLaunch.preservedStage,true);assert.equal(input.actorInputRows,undefined);assert.equal(input.rosterStateServices,undefined);
  await OB64.cutsceneUI.loadScene(rom,ui,scene);const r=ui.runtimeByAssetId[scene.assetId];assert(r,JSON.stringify(ui.sourceErrors));assert.equal(r.outcome,'modeled-termination',JSON.stringify(r.missingInputs));assert.equal(r.states.length,count);assert.deepStrictEqual(r.missingInputs,[]);assert.equal(r.states.at(-1).runtime.terminalReason,'terminal-state-release');
  const first=OB64.cutsceneRuntime.evaluate(r,1),last=OB64.cutsceneRuntime.evaluate(r,count-1);assert.deepStrictEqual(first.sceneColor,{red:255,green:255,blue:255});assert.equal(first.actors.length,2);assert.equal(last.actors[1].bank,changedBank);assert.equal(first.background.environmentSelector,0);
  assert.equal(ui.romStartupByAssetId[scene.assetId],'preserved-stage');assert(OB64.cutsceneUI.playbackTimingLabel(ui,scene).includes('level-one Hero and Fighter'));
  assert.equal(r.limits.maxStateBytes,128*1024*1024);assert(r.retainedStateBytes<r.limits.maxStateBytes);assert.equal(r.preservedStageMemory.arenaLimitBytes,524288);assert(r.preservedStageMemory.workingBytes<=655360);assert.equal(r.preservedStageMemory.retainedPerSnapshotBytes,0);assert.equal(r.preservedStageMemory.released,true);assert(!owned.at(-1).live);assert.equal(owned.at(-1).byteLength(),0);assert.throws(()=>owned.at(-1).height(0,0),/released/);
  const before=OB64.cutsceneRuntime.evaluate(r,100);before.actors[0].x=9999;before.nativeExternal.dialogue.memory[0].hex='bad';assert.notEqual(OB64.cutsceneRuntime.evaluate(r,100).actors[0].x,9999);assert.notEqual(OB64.cutsceneRuntime.evaluate(r,100).nativeExternal.dialogue.memory[0].hex,'bad');
  async function compose(tick){const preview=OB64.cutsceneRuntime.evaluate(r,tick),backgrounds=[];for(const layer of preview.background.layers){const image=await OB64.cutsceneUI.decodeImageAsset(rom,ui,ui.catalog.getImageAsset(layer.assetId));assert(image.renderable);backgrounds.push({layer,image});}const actorFrames=OB64.cutsceneSprites.framesForPreview(ui.spriteState,preview);assert.equal(Object.keys(actorFrames).length,2);const options={showMovementPaths:false,backgrounds,backgroundProjection:preview.background.projection,actorFrames,scenePropFrames:[],effectFrames:[],projection:preview.actorProjection,camera:preview.cameraState,overlays:preview.overlays,colorModulation:preview.sceneColor,screenTransition:preview.screenTransition};const target=OB64.cutsceneRenderer.renderFrame(p.document,preview,options),empty=OB64.cutsceneRenderer.renderFrame(p.document,preview,{...options,actorFrames:{}});assert(target.rgba.some((x,i)=>i%4!==3&&x>0),'visible Stage');assert(target.rgba.some((x,i)=>x!==empty.rgba[i]),'visible Actor pixels');const dialogue=OB64.cutsceneUI.composeDialogue(rom,ui,preview,true);dialogue.rows.forEach(row=>OB64.cutsceneDialogueDraw.paint(target,row));return target.rgba;}
  const images=[await compose(1),await compose(id==='01F450D0'?350:500)];assert.notDeepStrictEqual(...images);if(id==='01F4C45A'){await compose(310);const drawn=OB64.cutsceneUI.composeDialogue(rom,ui,OB64.cutsceneRuntime.evaluate(r,310),true);assert(drawn.rows.some(row=>row.commands.some(c=>c.texture.mirrorY&&c.uv[1]===19)));}
  runs.push({scene,p,input,r});
 }
 const {scene,p,input,r}=runs[0],renamed={...scene,assetId:'test-preserved-unrelated-name',friendlyName:'unrelated'},rp=OB64.cutsceneCodec.projectSceneDocument(renamed,await OB64.cutsceneCodec.loadSceneSource(z64,scene),ui.catalog),ri=OB64.cutsceneRomStart.input(z64,renamed,rp.program),rr=OB64.cutsceneRuntime.compile(rp.document,rp.program,renamed,ui.catalog,{z64,nativeLaunchInputs:ri,maxTicks:120});
 const facts=s=>({actors:s.actors.map(a=>[a.slot,a.bank,a.baseX,a.baseY,a.baseZ,a.displayedFrameToken]),color:s.sceneColor,camera:s.actorProjection});assert.deepStrictEqual(facts(rr.states[100]),facts(r.states[100]));
 const bad=structuredClone(p.program);bad.primitives.unshift({opcode:0x80000006,rawWords:[0x80000006,0]});assert.equal(OB64.cutsceneRomStart.analyze(bad).code,'rom-start-preserved-setup');
 const broken=z64.slice();broken[0x1f30b8]^=1;assert.throws(()=>new Stage(broken),/qualified/);
 const base=new Stage(z64),changed=z64.slice(),v=new DataView(changed.buffer),statOffset=0x5db20+2*72+8;v.setUint16(statOffset,v.getUint16(statOffset)+1);const edited=new Stage(changed);assert.equal(edited.machine.get(0x80193bc0+2*56+0x20,2),base.machine.get(0x80193bc0+2*56+0x20,2)+1,'current ROM character initialization');const freed=base.leases.find(r=>r.freed);assert(freed);assert.throws(()=>base.read(freed.address,1),/requires supplied memory/);base.machine.r[4]=524289;assert.throws(()=>base.service(0x80070f30,base.machine),/supported|bound|exceeds/);base.dispose();edited.dispose();
 const cancel=new AbortController(),materialize=Stage.prototype.materialize;let entered=false;Stage.prototype.materialize=function(...args){const result=materialize.apply(this,args);entered=true;cancel.abort();return result;};try{await assert.rejects(OB64.cutsceneRuntime.compileAsync(p.document,p.program,scene,ui.catalog,{z64,nativeLaunchInputs:input,signal:cancel.signal}),e=>e.name==='AbortError');}finally{Stage.prototype.materialize=materialize;}assert(entered);assert(!owned.at(-1).live);assert.equal(owned.at(-1).byteLength(),0);
 const second=runs[1],supplied=structuredClone(second.input);supplied.externalProducers.value.resourceSchedule.pageAdvancePolicy='neutral';OB64.cutsceneUI.setNativeLaunchInputs(ui,second.scene,supplied);await OB64.cutsceneUI.loadScene(rom,ui,second.scene);assert.equal(ui.romStartupByAssetId[second.scene.assetId],false);assert.equal(ui.runtimeByAssetId[second.scene.assetId].outcome,'awaiting-dialogue-input');OB64.cutsceneUI.setNativeLaunchInputs(ui,second.scene,null);await OB64.cutsceneUI.loadScene(rom,ui,second.scene);assert.equal(ui.runtimeByAssetId[second.scene.assetId].states.length,627);
 assert(retained.length>=4);console.log(JSON.stringify({status:'pass',runs:runs.map(x=>({label:OB64.cutsceneCatalog.displayName(x.scene),passes:x.r.states.length,actors:x.r.states.at(-1).actors.length,retainedStateBytes:x.r.retainedStateBytes,stageMemory:x.r.preservedStageMemory})),nativeStagePreserved:true,currentRomCharacterMutation:true,visibleActors:true,upperSpeechPointer:true,identityIndependent:true,immutableSeeking:true,arenaBound:true,cancelReleasesStage:true,importedPriority:true}));
 }finally{OB64.cutsceneDirectorLaunch.prototype.initialize=initialize;OB64.cutscenePreservedStage=Stage;}
})().catch(e=>{console.error(e.stack);process.exitCode=1;});
