'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert'),R=path.resolve(__dirname,'../..');
new Function('require','__dirname',fs.readFileSync(path.join(__dirname,'cutscene-shared-rom-start.test.js'),'utf8').split('\n(async()=>')[0])(require,__dirname);
const uiSource=fs.readFileSync(path.join(R,'editor/cutscene-ui.js'),'utf8');vm.runInThisContext(uiSource.replace('    loadScene: loadScene,','    loadScene: loadScene, testRenderStageArea: renderStageArea, testUpdateTransport: updateTransport,'));
function element(tag){return {tag,style:{},children:[],listeners:{},attrs:{},classList:{toggle(){}},appendChild(e){this.children.push(e);return e;},setAttribute(k,v){this.attrs[k]=v;},addEventListener(k,f){this.listeners[k]=f;},getBoundingClientRect(){return {left:0,top:0,width:320,height:240};}};}
const text=e=>[e.textContent||'',...e.children.map(text)].join(' ');
(async()=>{
 const raw=fs.readFileSync(path.join(R,'Ogre Battle 64 - Person of Lordly Caliber (U) [!].v64')),z64=new Uint8Array(raw.length);for(let i=0;i<raw.length;i+=2){z64[i]=raw[i+1];z64[i+1]=raw[i];}
 const rom={z64,archives:OB64.findArchives(z64),layout:{id:'us-rev0'}},ui=OB64.cutsceneUI.initialize(rom),scene=ui.catalog.getScene('rom-director:01F440B2'),source=await OB64.cutsceneCodec.loadSceneSource(z64,scene),p=OB64.cutsceneCodec.projectSceneDocument(scene,source,ui.catalog);
 assert.equal(p.program.primitives.at(-1).rawWords.at(-1),0xff000004);assert(OB64.cutsceneRomStart.supports({...scene,assetId:'unrelated-room-identity'},p.program));
 for(const [change,code] of [[q=>q.primitives.splice(2,1),'rom-start-room-camera'],[q=>q.primitives[1].rawWords[1]=0xffffffff,'rom-start-room-group'],[q=>q.primitives.shift(),'rom-start-room-media'],[q=>q.primitives.at(-1).rawWords[1]=0xff000006,'rom-start-class']]){const q=structuredClone(p.program);change(q);assert.equal(OB64.cutsceneRomStart.analyze(q).code,code);}
 ui.selectedSceneId=scene.sceneId;
 const doc=await OB64.cutsceneUI.loadScene(rom,ui,scene),run=ui.runtimeByAssetId[scene.assetId];assert(run,JSON.stringify(ui.sourceErrors));assert.equal(run.states.length,997);assert.equal(run.outcome,'external-input');assert.equal(run.unresolvedQuery.nodeId,'node:01F440B2:w0238');assert.equal(run.missingInputs.length,1);assert.deepStrictEqual(ui.sourceErrors,{});assert.equal(ui.romStartupByAssetId[scene.assetId],'room');
 const sample=OB64.cutsceneRuntime.evaluate(run,23);assert.equal(sample.actors.length,8);assert.equal(sample.nativeActorDrawing.actors.length,8);assert.deepStrictEqual(sample.background.layers.map(x=>x.nativeOrdinal),[0,1,3,4,5,6]);assert(sample.background.layers.every(x=>x.renderPipeline==='mode-zero-b5-actor-camera'));
 const image=await OB64.cutsceneUI.capturePreviewFrame(rom,ui,doc,{preview:sample,pass:23,nodeId:'room-check',backgroundPolicy:'require'});assert(!image.error);assert(image.rgba.some((x,i)=>i%4!==3&&x));sample.actors[0].x=99999;assert.notEqual(OB64.cutsceneRuntime.evaluate(run,23).actors[0].x,99999);
 global.document={createElement:element};ui.ui={};const shell=element('main');OB64.cutsceneUI.testRenderStageArea(shell,rom,ui,scene,doc);assert.equal(ui.ui.playButton.textContent,'Play');assert(text(shell).includes('Animated Path Ribbon Activity Query'));assert(!text(shell).includes('Approximate storyboard only'));assert(text(shell).includes('Preview Army'));ui.ui.clock.playing=true;OB64.cutsceneUI.testUpdateTransport(ui,{frame:0,durationFrames:997});assert.equal(ui.ui.playButton.textContent,'Pause');delete global.document;ui.ui=null;
 // Explicit names and controller policy keep priority over generated defaults.
 const input=OB64.cutsceneRomStart.input(z64,scene,p.program),custom=structuredClone(input);custom.externalProducers.value.directorLaunch.previewArmyName='Custom Army';custom.externalProducers.value.resourceSchedule.pageAdvancePolicy='neutral';const before=JSON.stringify(custom);
 OB64.cutsceneUI.setNativeLaunchInputs(ui,scene,custom);await OB64.cutsceneUI.loadScene(rom,ui,scene);assert.equal(ui.romStartupByAssetId[scene.assetId],false);assert.equal(ui.runtimeByAssetId[scene.assetId].outcome,'awaiting-dialogue-input');assert.equal(JSON.stringify(custom),before);
 const named=OB64.cutsceneRuntime.evaluate(ui.runtimeByAssetId[scene.assetId],61),memory=named.nativeExternal.dialogue.memory;let army='';for(let i=0;i<16;i++){const address=0x80196a58+i,row=memory.find(r=>address>=r.address&&address<r.address+r.hex.length/2),value=parseInt(row.hex.slice((address-row.address)*2,(address-row.address)*2+2),16);if(!value)break;army+=String.fromCharCode(value);}assert.equal(army,'Custom Army');
 // Obsolete work cancels without altering the supplied input or retained frames.
 const cancel=new AbortController(),prepare=OB64.cutsceneSharedActor.prototype.prepare;let reached=false;OB64.cutsceneSharedActor.prototype.prepare=function(...args){const result=prepare.apply(this,args);reached=true;cancel.abort();return result;};try{await assert.rejects(OB64.cutsceneRuntime.compileAsync(p.document,p.program,scene,ui.catalog,{z64,nativeLaunchInputs:input,maxTicks:80,signal:cancel.signal}),e=>e.name==='AbortError');}finally{OB64.cutsceneSharedActor.prototype.prepare=prepare;}assert(reached);
 OB64.cutsceneUI.setNativeLaunchInputs(ui,scene,null);await OB64.cutsceneUI.loadScene(rom,ui,scene);assert.equal(ui.runtimeByAssetId[scene.assetId].states.length,997);assert.equal(ui.romStartupByAssetId[scene.assetId],'room');assert(!ui.sourceErrors['runtime-context:'+scene.assetId]);
 // Disable the optional fresh-start shortcut to exercise predecessor-error attribution.
 // This control does not execute an otherwise supported ancestor as another full scene.
 const retailProgram=ui.programByAssetId[scene.assetId],incomplete=structuredClone(retailProgram);incomplete.primitives.splice(2,1);ui.programByAssetId[scene.assetId]=incomplete;const eligibility=OB64.cutsceneRomStart.supports;OB64.cutsceneRomStart.supports=()=>false;try{await OB64.cutsceneUI.loadScene(rom,ui,scene);}finally{OB64.cutsceneRomStart.supports=eligibility;}assert(!ui.runtimeByAssetId[scene.assetId]);assert(ui.sourceErrors['runtime-context:'+scene.assetId].includes('Preceding Director rom-director:01FAA544'));assert(ui.sourceErrors['runtime-context:'+scene.assetId].includes('terminal resource class 6'));ui.programByAssetId[scene.assetId]=retailProgram;await OB64.cutsceneUI.loadScene(rom,ui,scene);assert.equal(ui.runtimeByAssetId[scene.assetId].states.length,997);assert(!ui.sourceErrors['runtime-context:'+scene.assetId]);
 console.log(JSON.stringify({predecessorErrorAttribution:true,status:'pass',states:997,actors:8,layers:6,boundary:'Animated Path Ribbon Activity Query',ordinaryPlay:true,preciseStageBoundary:true,explicitArmyName:army,neutralInputPreserved:true,cancellation:true,repeatedSelection:true,identityIndependent:true,missingCameraAndInheritedSelectorRejected:true}));
})().catch(e=>{console.error(e.stack);process.exitCode=1;});
