'use strict';
const assert = require('assert'), fs = require('fs'), path = require('path'), vm = require('vm');
const { installDom } = require('./helpers/editor-dom');
global.window = global; global.btoa = value => Buffer.from(value, 'binary').toString('base64'); global.atob = value => Buffer.from(value, 'base64').toString('binary');
vm.runInThisContext('var OB64 = window.OB64 = {};');
for (const file of ['editor-interaction.js','art.js','sprite-library.js','sprite-editor-ui.js']) vm.runInThisContext(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),{filename:file});
const L = OB64.spriteLibrary, E = OB64.editorInteraction, U = OB64.spriteEditorUI;
const state = L.createState();
let asset = L.addAsset(state,L.blankAsset(state,{name:'Geometry',width:4,height:2}));
const id = asset.id, pixels = new Uint8ClampedArray(32); pixels.set([248,0,0,255],0); pixels.set([0,248,0,128],28);
L.replaceLayerPixels(state,id,0,0,pixels); L.setAnchor(state,id,1,1); L.setLayerPosition(state,id,0,0,-1,2);
const before = L.assetFileText(asset);
const preview = L.previewGeometry(asset,'canvas',8,6,'center',false);
assert.strictEqual(L.assetFileText(asset),before); assert.deepStrictEqual(preview.frames[0].layers[0].pixels,pixels);
assert.deepStrictEqual(preview.anchor,{x:3,y:3}); assert.strictEqual(preview.frames[0].layers[0].x,1);
L.resizeCanvas(state,id,8,6,'center',false); assert.strictEqual(asset.frames[0].layers[0].x-asset.anchor.x,-2);
L.undo(state,id); asset=L.assetFor(state,id); assert.strictEqual(L.assetFileText(asset),before);
L.resizeCanvas(state,id,2,2,'top-left',true); assert.strictEqual(asset.frames[0].layers[0].pixels.length,16);
L.undo(state,id); asset=L.assetFor(state,id); assert.strictEqual(L.assetFileText(asset),before);
assert.throws(()=>L.resizeCanvas(state,id,0,2,'center',false)); assert.strictEqual(L.assetFileText(asset),before);
const scaled = L.previewGeometry(asset,'scale',8,4); assert.strictEqual(scaled.frames[0].layers[0].width,8); assert.deepStrictEqual(scaled.anchor,{x:2,y:2});
const other = L.addAsset(state,L.blankAsset(state,{name:'Other',width:2,height:2}));
L.removeAsset(state,id); L.renameAsset(state,other.id,'Later unrelated edit'); L.undoDelete(state);
assert.strictEqual(L.assetFileText(L.assetFor(state,id)),before); assert.strictEqual(L.assetFor(state,other.id).name,'Later unrelated edit');
assert(L.undo(state,id),'restored editing history'); assert.strictEqual(L.assetFor(state,id).frames[0].layers[0].x,0);
L.redo(state,id); L.removeAsset(state,id); const snapshot=state.deletedAssets[0].asset; L.addAsset(state,L.cloneAsset(snapshot));
assert.throws(()=>L.undoDelete(state),/identity/); assert.strictEqual(state.deletedAssets.length,1);
L.removeAsset(state,id); L.undoDelete(state); assert.throws(()=>L.undoDelete(state),/identity/);
const payload=L.collectProjectPayload({spriteLibrary:state}); L.applyPreparedProjectPayload({spriteLibrary:state},L.prepareProjectPayload(payload));
assert.strictEqual(L.undoDelete(state),null,'Project load clears recovery');
console.log('PASS U3/U6 geometry, cancellation, crop undo, deletion recovery/history, unrelated edits, identity and Project boundaries');
const dom=installDom();
const model={identity:'a',playing:false,speed:1,ms:0,frame:0};
const frames=[{ticks:0},{ticks:2},{ticks:1}], seenA=[],seenB=[];
const host=document.createElement('section');document.body.appendChild(host);
const transport=E.mountTransport(host,model,frames,index=>seenA.push(index),{identity:'a'});
const compare=document.createElement('section');document.body.appendChild(compare);
E.mountTransport(compare,model,[{ticks:1},{ticks:5}],index=>seenB.push(index),{identity:'b',controls:false});
assert.strictEqual(E.frameAt(frames,0),1); assert.strictEqual(E.frameAt([{ticks:0},{ticks:0}],1e12),0);
dom.findText(host,'Play').click(); assert.strictEqual(dom.scheduled.size,1,'one shared scheduled timeline');dom.tick(0);dom.tick(70);
assert.strictEqual(seenA.at(-1),2);assert.strictEqual(seenB.at(-1),1);
dom.findText(host,'Pause').click(); const paused=model.ms;dom.tick(200);assert.strictEqual(model.ms,paused,'paused timeline must not advance');
transport.seek(0);assert.strictEqual(seenA.at(-1),0,'zero-duration frame can be selected');
dom.findText(host,'Next frame').click();assert.strictEqual(seenA.at(-1),1);
const speed=host.querySelector('select');speed.value='2';speed.dispatch('change');assert.strictEqual(model.speed,2);
dom.findText(host,'Play').click();host.remove();compare.remove();dom.tick(300);assert.strictEqual(dom.scheduled.size,0);
console.log('PASS U2 shared durations, zero-duration stepping, pause/speed, one scheduler, and removed-preview cleanup');
const rom={spriteLibrary:L.createState()};asset=L.addAsset(rom.spriteLibrary,L.blankAsset(rom.spriteLibrary,{name:'Keyboard',width:4,height:4}));
const ui=rom.spriteLibrary.ui;Object.assign(ui,{frameIndex:0,layerIndex:0,zoom:4,color:[248,0,0,255],brushSize:1,background:'checkerboard',showGrid:false,tool:'pencil'});
const canvas=document.createElement('canvas');document.body.appendChild(canvas);let changes=0;
U.installCanvasEditing(canvas,rom.spriteLibrary,asset,ui,{onChange(){changes++;}},()=>{});
canvas.dispatch('keydown',{key:'ArrowRight'});canvas.dispatch('keydown',{key:' '});assert.strictEqual(L.assetFor(rom.spriteLibrary,asset.id).frames[0].layers[0].pixels[4],248);
// Reinstall after a normal rerender to use the current layer snapshot.
canvas.remove();const next=document.createElement('canvas');document.body.appendChild(next);asset=L.assetFor(rom.spriteLibrary,asset.id);
U.installCanvasEditing(next,rom.spriteLibrary,asset,ui,{onChange(){changes++;}},()=>{});
next.dispatch('keydown',{key:'i'});assert.deepStrictEqual(ui.color,[248,0,0,255]);next.dispatch('keydown',{key:'ArrowDown',shiftKey:true});assert.deepStrictEqual(ui.selection,{x:1,y:0,width:1,height:2});
const saved=L.assetFileText(asset);next.dispatch('keydown',{key:' ',target:document.createElement('input')});assert.strictEqual(L.assetFileText(asset),saved,'typing elsewhere cannot paint');
next.dispatch('keydown',{key:'Delete'});assert.strictEqual(changes,1,'erasing already-transparent pixel creates no edit');
const launcher=document.createElement('button');document.body.appendChild(launcher);launcher.focus();const overlay=document.createElement('div');
const one=document.createElement('button'),two=document.createElement('button');overlay.append(one,two);E.bindDialog(overlay);document.body.appendChild(overlay);two.focus();overlay.dispatch('keydown',{key:'Tab'});assert.strictEqual(document.activeElement,one);
one.focus();overlay.dispatch('keydown',{key:'Tab',shiftKey:true});assert.strictEqual(document.activeElement,two);overlay.remove();E.releaseDialog(overlay);assert.strictEqual(document.activeElement,launcher);
console.log('PASS U4 keyboard paint/sample/selection, typing isolation, modal focus containment and return');
const panel=document.createElement('main');document.body.appendChild(panel);U.render(panel,rom,{onChange(){changes++;}},false);
assert(panel.querySelector('.sprite-used-color-grid'));assert.strictEqual(panel.querySelectorAll('.sprite-used-color-grid')[0].children.filter(row=>row.tabIndex===0).length,1);
const name=panel.querySelector('[data-sprite-focus-key="asset-name"]');name.focus();name.setSelectionRange(2,4);panel.querySelector('.sprite-canvas-scroll').scrollTop=13;
U.render(panel,rom,{},true);assert.strictEqual(document.activeElement.getAttribute('data-sprite-focus-key'),'asset-name');assert.strictEqual(document.activeElement.selectionStart,2);assert.strictEqual(document.activeElement.selectionEnd,4);assert.strictEqual(panel.querySelector('.sprite-canvas-scroll').scrollTop,13);
console.log('PASS U1/U4 actual Sprite Editor swatches and semantic focus/caret/scroll across rerender');

// Capacity rejection must leave the deletion entry available for later recovery.
const full=L.createState(), deleted=L.addAsset(full,L.blankAsset(full,{name:'Recover',width:1,height:1}));L.removeAsset(full,deleted.id);
for(let i=0;i<512;i++) L.addAsset(full,L.blankAsset(full,{name:'Entry '+i,width:1,height:1}));
assert.throws(()=>L.undoDelete(full),/limit/);assert.strictEqual(full.deletedAssets.length,1);assert.strictEqual(full.assets.length,512);
console.log('PASS U6 active asset capacity rejection preserves deletion recovery');
// Actual geometry dialog: rejected dimensions and cancellation do not mutate; application is undoable.
const geomAsset=L.assetFor(rom.spriteLibrary,rom.spriteLibrary.ui.assetId), geomBefore=L.assetFileText(geomAsset);
launcher.focus();U.openGeometryModal(rom.spriteLibrary,geomAsset,rom.spriteLibrary.ui,{},()=>{},'canvas');
let geom=document.body.querySelector('[role="dialog"]'), outputWidth=geom.querySelector('[aria-label="Output width"]');
outputWidth.value='0';outputWidth.dispatch('input');assert(dom.findText(geom,'Canvas Size').tagName==='H2' || geom.textContent.includes('Blocked'));
assert.strictEqual(L.assetFileText(geomAsset),geomBefore);geom.querySelectorAll('button').find(row=>row.textContent==='Cancel').click();assert.strictEqual(L.assetFileText(geomAsset),geomBefore);
U.openGeometryModal(rom.spriteLibrary,geomAsset,rom.spriteLibrary.ui,{},()=>{},'canvas');geom=document.body.querySelector('[role="dialog"]');
geom.querySelector('[aria-label="Output width"]').value='6';geom.querySelector('[aria-label="Output width"]').dispatch('input');
assert(geom.textContent.includes('Affects all 1 frames'));geom.querySelectorAll('button').find(row=>row.textContent==='Canvas Size').click();
assert.strictEqual(L.assetFor(rom.spriteLibrary,geomAsset.id).width,6);L.undo(rom.spriteLibrary,geomAsset.id);assert.strictEqual(L.assetFileText(L.assetFor(rom.spriteLibrary,geomAsset.id)),geomBefore);
console.log('PASS U3 actual preview dialog, invalid dimensions, cancel, apply and undo');
const colorful=new Uint8ClampedArray(32*16*4);for(let i=0;i<512;i++) colorful.set([i&255,i>>8,32,255],i*4);
const paletteAsset=L.addAsset(rom.spriteLibrary,L.assetFromRgba(rom.spriteLibrary,{name:'512 colors',width:32,height:16,rgba:colorful}));
U.render(panel,rom,{},false);let colorGrid=panel.querySelector('.sprite-used-color-grid');assert.strictEqual(colorGrid.children.length,256);
assert.strictEqual(colorGrid.children.filter(row=>row.tabIndex===0).length,1);colorGrid.children[0].focus();colorGrid.children[0].dispatch('keydown',{key:'ArrowRight'});assert.strictEqual(document.activeElement,colorGrid.children[1]);
colorGrid.children[1].click();colorGrid=panel.querySelector('.sprite-used-color-grid');assert.strictEqual(colorGrid.children.filter(row=>row.tabIndex===0).length,1);assert(colorGrid.children[1].classList.contains('selected'));
dom.findText(panel,'Next colors').click();assert.strictEqual(rom.spriteLibrary.ui.usedColorPage,1);assert.strictEqual(panel.querySelector('.sprite-used-color-grid').children.length,256);
const scopeControl=panel.querySelector('[data-sprite-focus-key="used-color-scope"]');scopeControl.value='sequence';scopeControl.dispatch('change');assert.strictEqual(rom.spriteLibrary.ui.usedColorScope,'sequence');assert.strictEqual(rom.spriteLibrary.ui.usedColorPage,0);
console.log('PASS U1 512-color paging, one roving keyboard stop, selected swatch, and scope persistence');

L.addFrame(rom.spriteLibrary,paletteAsset.id,0,true);U.render(panel,rom,{},true);
let inline=panel.querySelector('.sprite-inline-preview');dom.findText(inline,'Play').click();assert.strictEqual(dom.scheduled.size,1);
U.render(panel,rom,{},true);assert.strictEqual(dom.scheduled.size,1,'rerender replaces scheduled work');assert(rom.spriteLibrary.ui.playback.playing);
panel.querySelectorAll('.sprite-frame-card')[1].click();assert.strictEqual(rom.spriteLibrary.ui.frameIndex,1);assert(!rom.spriteLibrary.ui.playback.playing);assert.strictEqual(dom.scheduled.size,0);
const only=L.addAsset(rom.spriteLibrary,L.blankAsset(rom.spriteLibrary,{name:'One frame',width:2,height:2}));U.render(panel,rom,{},true);
assert(dom.findText(panel.querySelector('.sprite-inline-preview'),'Play').disabled);assert.strictEqual(rom.spriteLibrary.ui.playback.identity,only.id);
const stroke=panel.querySelector('.sprite-edit-canvas'), strokeBefore=L.assetFileText(only);Object.assign(rom.spriteLibrary.ui,{tool:'pencil',color:[128,64,32,255]});
stroke.dispatch('pointerdown',{pointerId:9,clientX:1,clientY:1});stroke.dispatch('pointercancel',{pointerId:9});assert.strictEqual(L.assetFileText(only),strokeBefore);assert(!stroke.hasPointerCapture(9));
const released=panel.querySelector('.sprite-edit-canvas');released.dispatch('pointerdown',{pointerId:10,clientX:1,clientY:1});released.dispatch('pointerup',{pointerId:10,clientX:10000,clientY:10000});assert(!released.hasPointerCapture(10));assert.notStrictEqual(L.assetFileText(only),strokeBefore);L.undo(rom.spriteLibrary,only.id);assert.strictEqual(L.assetFileText(L.assetFor(rom.spriteLibrary,only.id)),strokeBefore);
console.log('PASS U2/U4 actual transport rerender, frame/asset changes, single-frame state, pointer cancellation/outside release and undo');

U.openLibraryPicker(rom,{},()=>{});let picker=document.body.querySelector('[role="dialog"]');
const pickerSelect=picker.querySelector('select');pickerSelect.value=paletteAsset.id;pickerSelect.dispatch('change');
let pickerFrame=picker.querySelectorAll('.sprite-frame-card')[1];pickerFrame.focus();pickerFrame.click();
assert(document.activeElement.isConnected && document.activeElement.classList.contains('sprite-frame-card'),'picker rebuild retains frame-card focus');
picker.querySelectorAll('button').find(row=>row.textContent==='Cancel').click();
console.log('PASS U4 rebuilt library-picker frame focus');
