'use strict';

// Static acceptance for the shared OBMB neutral-runtime composer. This test
// reads the retail ROM and generated bytes only. It never starts an emulator.

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const EDITOR = path.resolve(__dirname, '..');
const ROOT = path.resolve(EDITOR, '..');
const MASTER = path.join(ROOT, 'Ogre Battle 64 - Person of Lordly Caliber (U) [!].v64');

global.window = global;
global.localStorage = { getItem() { return null; }, setItem() {}, removeItem() {} };
vm.runInThisContext('var OB64 = window.OB64 = window.OB64 || {};');
for (const filename of [
  'data.js', 'parsers.js', 'repack.js', 'description-codec.js',
  'consumable-effects.js', 'patch.js', 'squadblob.js', 'runtimeblob.js',
]) {
  const fullPath = path.join(EDITOR, filename);
  vm.runInThisContext(fs.readFileSync(fullPath, 'utf8'), { filename: fullPath });
}

const masterV64 = new Uint8Array(fs.readFileSync(MASTER));
const masterZ64 = OB64.normalizeRomImage(masterV64).z64;
const rev0 = OB64.cloneRomLayout(OB64.ROM_LAYOUTS['us-rev0']);
const rev1 = OB64.cloneRomLayout(OB64.ROM_LAYOUTS['us-rev1']);
const C = OB64.runtimeOverrides.consts;
let failures = 0;

function check(name, condition, detail) {
  console.log((condition ? 'PASS' : 'FAIL') + '  ' + name +
    (condition || !detail ? '' : ' - ' + detail));
  if (!condition) failures++;
}

function throws(name, fn, pattern) {
  try {
    fn();
    check(name, false, 'did not throw');
  } catch (error) {
    check(name, pattern.test(error.message), error.message);
  }
}

function equalBytes(a, b) {
  if (!a || !b || a.length !== b.length) return false;
  for (let index = 0; index < a.length; index++) if (a[index] !== b[index]) return false;
  return true;
}

function applyWrites(z64, plan) {
  plan.writes.forEach(write => z64.set(write.bytes, write.offset));
}

function planDigest(plan) {
  const pieces = [];
  plan.writes.forEach(write => {
    const header = Buffer.alloc(8);
    header.writeUInt32BE(write.offset >>> 0, 0);
    header.writeUInt32BE(write.bytes.length >>> 0, 4);
    pieces.push(header, Buffer.from(write.bytes));
  });
  return crypto.createHash('sha256').update(Buffer.concat(pieces)).digest('hex').toUpperCase();
}

function u16(bytes, offset) { return ((bytes[offset] << 8) | bytes[offset + 1]) >>> 0; }
function u32(bytes, offset) { return OB64.readU32BE(bytes, offset) >>> 0; }
function cloneJson(value) { return JSON.parse(JSON.stringify(value)); }
function makeRom(layout, z64) {
  return { layout: OB64.cloneRomLayout(layout), z64: z64 || masterZ64.slice() };
}

function makeSquadOverride(index) {
  const original = new Uint8Array(35);
  const record = new Uint8Array(35);
  original[0] = (index % 0xA4) + 1;
  record.set(original);
  record[34] = (index + 1) & 0xFF;
  return { runtimeKey: index, edatId: index, gateId: index & 0xFF, original, record };
}

function customMembersFixture() {
  return [
    { classId: 0x05, levelOffsetRaw: 1, cell: 6, cohort: 'A' },
    { classId: 0x47, levelOffsetRaw: 0, cell: 8, cohort: 'B' },
    { classId: 0x10, levelOffsetRaw: 0, cell: 2, cohort: 'C' },
    { classId: 0x10, levelOffsetRaw: 0, cell: 0, cohort: 'C' },
  ];
}

function customEquipmentFixture() {
  return { A: [0x10, 0x11], B: [0x20, 0], C: [0x30, 0x31] };
}

function customBonusesFixture() {
  return [
    { classId: 0x05, bonus: 15 },
    { classId: 0x10, bonus: 25 },
    { classId: 0x11, bonus: 40 },
  ];
}

function customRewardsFixture() {
  return { slots: [
    { raw: 0x8001, weight: 1 },
    { raw: 0x0002, weight: 2 },
    { raw: 0x0000, weight: 3 },
  ] };
}

const parsedRetail = OB64.parseNeutralEncounters(masterZ64);
const validScenarioRows = parsedRetail.scenarioRates.filter(row => Number.isInteger(row.slice));
const aliasesBySlice = {};
validScenarioRows.forEach(row => {
  (aliasesBySlice[row.slice] = aliasesBySlice[row.slice] || []).push(row);
});
const aliasRows = Object.values(aliasesBySlice).find(rows => rows.length >= 2);
if (!aliasRows) throw new Error('Retail scenario metadata has no shared neutral slice fixture.');
const scenarioA = aliasRows[0];
const scenarioB = aliasRows[1];

const scenarioRates = [
  {
    runtimeKey: scenarioA.runtimeKey,
    normal: { mode: 'override', passCount: 101, divisor: 72000 },
    alternate: { mode: 'disabled', passCount: null, divisor: null },
  },
  {
    runtimeKey: scenarioB.runtimeKey,
    normal: { mode: 'disabled', passCount: null, divisor: null },
    alternate: { mode: 'override', passCount: 7, divisor: 1000 },
  },
];
const weightedOverrides = [
  { classId: 0x45, weights: [1, 2, 3] },
  { classId: 0x46, weights: [0, 5, 0] },
];
const customProfiles = [{
  profileId: 1,
  runtimeKey: scenarioA.runtimeKey,
  slice: scenarioA.slice,
  terrainSlot: 2,
  members: customMembersFixture(),
  equipment: customEquipmentFixture(),
  label: 'Bandits!',
  persuasion: {
    mode: 'fixed', chance: 37, classBonuses: customBonusesFixture(),
  },
  retreat: { hpThreshold: 25 },
  rewards: customRewardsFixture(),
}];
const defaultPersuasionProfile = OB64.runtimeOverrides.normalizeCustomProfile({
  profileId: 2,
  runtimeKey: scenarioB.runtimeKey,
  slice: scenarioB.slice,
  terrainSlot: 3,
  members: customMembersFixture(),
  equipment: customEquipmentFixture(),
}, 0);
check('custom squads without an edited persuasion value normalize to fixed ten percent',
  defaultPersuasionProfile.persuasion.mode === 'fixed' &&
  defaultPersuasionProfile.persuasion.chance === 10);
check('custom squads default to never retreating',
  defaultPersuasionProfile.retreat.hpThreshold === 0);
check('custom squads default to three equally weighted no-reward choices',
  JSON.stringify(defaultPersuasionProfile.rewards.slots) === JSON.stringify([
    { raw: 0, weight: 1 }, { raw: 0, weight: 1 }, { raw: 0, weight: 1 },
  ]));
const shopOverrides = [{ shopIndex: 2, items: [1, 2], consumables: [1, 8] }];

console.log('\n-- retail hooks and legacy OBM2 stability --');
const rev0Layout = OB64.runtimeOverrides.patchLayout(rev0);
check('Rev 0 retail rate hook matches the byte-proven RNG call',
  u32(masterZ64, rev0Layout.RATE_HOOK_ROM) === 0x0C024A98 &&
  u32(masterZ64, rev0Layout.RATE_HOOK_ROM + 4) === 0);
check('Rev 0 retail drop hook matches the byte-proven RNG call',
  u32(masterZ64, rev0Layout.DROP_HOOK_ROM) === 0x0C024A98 &&
  u32(masterZ64, rev0Layout.DROP_HOOK_ROM + 4) === 0);
check('Rev 0 retreat hook starts after retail encounter and actor-validity checks',
  rev0Layout.RETREAT_HOOK_ROM === 0x214C50 &&
  u32(masterZ64, rev0Layout.RETREAT_HOOK_ROM) === C.RETREAT_ORIGINAL_WORDS[0] &&
  u32(masterZ64, rev0Layout.RETREAT_HOOK_ROM + 4) === C.RETREAT_ORIGINAL_WORDS[1]);
check('Rev 0 persuasion hook starts after retail target-eligibility checks',
  rev0Layout.PERSUASION_HOOK_ROM === 0x214A08 &&
  u32(masterZ64, rev0Layout.PERSUASION_HOOK_ROM) === C.PERSUASION_ORIGINAL_WORDS[0] &&
  u32(masterZ64, rev0Layout.PERSUASION_HOOK_ROM + 4) === C.PERSUASION_ORIGINAL_WORDS[1]);
check('Rev 0 Talk outcome states share the retail first-flagged target lookup',
  JSON.stringify(rev0Layout.PERSUASION_TARGET_HOOK_ROMS) ===
    JSON.stringify([0x219ADC, 0x219D34, 0x219D90]) &&
  rev0Layout.PERSUASION_TARGET_HOOK_ROMS.every(offset =>
    u32(masterZ64, offset) === C.PERSUASION_TARGET_ORIGINAL_WORDS[0] &&
    u32(masterZ64, offset + 4) === C.PERSUASION_TARGET_ORIGINAL_WORDS[1]));
check('Rev 0 cycle-budget hooks cover every safe Fight and Talk decrement',
  rev0Layout.FIGHT_BUDGET_HOOK_ROM === 0x215FB4 &&
  u32(masterZ64, rev0Layout.FIGHT_BUDGET_HOOK_ROM) ===
    C.FIGHT_BUDGET_ORIGINAL_WORDS[0] &&
  u32(masterZ64, rev0Layout.FIGHT_BUDGET_HOOK_ROM + 4) ===
    C.FIGHT_BUDGET_ORIGINAL_WORDS[1] &&
  rev0Layout.TALK_BUDGET_HOOK_ROM === 0x216168 &&
  u32(masterZ64, rev0Layout.TALK_BUDGET_HOOK_ROM) ===
    C.TALK_BUDGET_ORIGINAL_WORDS[0] &&
  u32(masterZ64, rev0Layout.TALK_BUDGET_HOOK_ROM + 4) ===
    C.TALK_BUDGET_ORIGINAL_WORDS[1] &&
  rev0Layout.FIGHT_RESULT_BUDGET_HOOK_ROM === 0x216458 &&
  u32(masterZ64, rev0Layout.FIGHT_RESULT_BUDGET_HOOK_ROM) ===
    C.FIGHT_BUDGET_ORIGINAL_WORDS[0] &&
  u32(masterZ64, rev0Layout.FIGHT_RESULT_BUDGET_HOOK_ROM + 4) ===
    C.FIGHT_BUDGET_ORIGINAL_WORDS[1]);
check('Rev 0 round-continuation hook replaces only the secondary native mode accessor',
  rev0Layout.LEGACY_ROUND_CONTINUATION_HOOK_ROM === 0x215C78 &&
  u32(masterZ64, rev0Layout.LEGACY_ROUND_CONTINUATION_HOOK_ROM) ===
    C.LEGACY_ROUND_CONTINUATION_ORIGINAL_WORDS[0] &&
  u32(masterZ64, rev0Layout.LEGACY_ROUND_CONTINUATION_HOOK_ROM + 4) ===
    C.LEGACY_ROUND_CONTINUATION_ORIGINAL_WORDS[1] &&
  rev0Layout.ROUND_CONTINUATION_HOOK_ROM === 0x221280 &&
  u32(masterZ64, rev0Layout.ROUND_CONTINUATION_HOOK_ROM) ===
    C.ROUND_CONTINUATION_ORIGINAL_WORDS[0] &&
  u32(masterZ64, rev0Layout.ROUND_CONTINUATION_HOOK_ROM + 4) ===
    C.ROUND_CONTINUATION_ORIGINAL_WORDS[1] &&
  rev0Layout.ROUND_CONTINUATION_RETAIL_MODE_LIVE === 0x801C8AFC);
check('Rev 0 command-menu hook wraps only its next-record callsite',
  rev0Layout.MENU_ITERATOR_HOOK_ROM === 0x215BCC &&
  u32(masterZ64, rev0Layout.MENU_ITERATOR_HOOK_ROM) ===
    C.MENU_ITERATOR_ORIGINAL_WORDS[0] &&
  u32(masterZ64, rev0Layout.MENU_ITERATOR_HOOK_ROM + 4) ===
    C.MENU_ITERATOR_ORIGINAL_WORDS[1] &&
  rev0Layout.MENU_ITERATOR_RETAIL_LIVE === 0x801D96A0 &&
  rev0Layout.MENU_STREAM_CONTEXT_PTR_LIVE === 0x801CE8C0);
check('Rev 0 reward hook starts at the retail slot-to-item mapping',
  rev0Layout.REWARD_HOOK_ROM === 0x1024B4 &&
  u32(masterZ64, rev0Layout.REWARD_HOOK_ROM) === C.REWARD_ORIGINAL_WORDS[0] &&
  u32(masterZ64, rev0Layout.REWARD_HOOK_ROM + 4) === C.REWARD_ORIGINAL_WORDS[1]);
check('Rev 0 message-text hook replaces only pointer resolution and assignment',
  rev0Layout.MESSAGE_TEXT_HOOK_ROM === 0x000E5AD4 &&
  u32(masterZ64, rev0Layout.MESSAGE_TEXT_HOOK_ROM) ===
    C.MESSAGE_TEXT_ORIGINAL_WORDS[0] &&
  u32(masterZ64, rev0Layout.MESSAGE_TEXT_HOOK_ROM + 4) ===
    C.MESSAGE_TEXT_ORIGINAL_WORDS[1]);

const legacyPlan = OB64.runtimeOverrides.buildRuntimeOverrideWrites(
  [], shopOverrides, 256, makeRom(rev0)
);
const legacyDigest = planDigest(legacyPlan);
check('four-argument shop composer preserves the frozen five-write OBM2 plan',
  legacyPlan.writes.length === 5 &&
  legacyPlan.sentinel === C.SHARED_SENTINEL &&
  !legacyPlan.writes.some(write => write.offset === rev0Layout.RATE_HOOK_ROM ||
    write.offset === rev0Layout.DROP_HOOK_ROM));
check('legacy shop-only plan retains its accepted byte digest',
  legacyDigest === '67AD3D51EF58FAAF39B315BBA657ACD6C0763C228B26BF8458B7127A876EF6B4',
  legacyDigest);

const managedLegacyPlan = OB64.runtimeOverrides.buildRuntimeOverrideWrites(
  [], shopOverrides, 256, makeRom(rev0), {
    scenarioRateOverrides: [], weightedDropOverrides: [], customNeutralSquads: [],
  }
);
check('explicit neutral ownership restores both neutral hooks without changing OBM2 payloads',
  managedLegacyPlan.writes.length === 7 && legacyPlan.writes.every(write => {
    const managed = managedLegacyPlan.writes.find(candidate => candidate.offset === write.offset);
    return managed && equalBytes(managed.bytes, write.bytes);
  }));

console.log('\n-- OBMB layout, direct scenario rates, and dispatch --');
const oneSquad = [makeSquadOverride(1)];
const mixedPlan = OB64.runtimeOverrides.buildRuntimeOverrideWrites(
  oneSquad, shopOverrides, 256, makeRom(rev0), {
    scenarioRateOverrides: scenarioRates,
    weightedDropOverrides: weightedOverrides,
    customNeutralSquads: customProfiles,
  }
);
check('mixed composer installs every OBMB client',
  mixedPlan.squadCount === 1 && mixedPlan.shopOverrideCount === 1 &&
  mixedPlan.scenarioRateOverrideCount === 2 &&
  mixedPlan.weightedDropOverrideCount === 2 &&
  mixedPlan.customNeutralSquadCount === 1 &&
  mixedPlan.sentinel === C.NEUTRAL_SHARED_SENTINEL && mixedPlan.writes.length === 24,
  JSON.stringify(mixedPlan.writes.map(write => [write.label, write.offset, write.bytes.length])));

const rateResolverBytes = OB64.squad.wordsToBytes(
  OB64.runtimeOverrides.buildRateResolver(rev0Layout)
);
const selectionResolverWords = OB64.runtimeOverrides.buildSelectionResolver(rev0Layout);
const dropResolverBytes = OB64.squad.wordsToBytes(
  OB64.runtimeOverrides.buildDropResolver(rev0Layout)
);
check('65-row rate table ends before the weighted-drop resolver',
  C.RATE_RESOLVER_OFF + rateResolverBytes.length <= C.RATE_TABLE_OFF &&
  C.RATE_TABLE_OFF + 8 + C.RATE_SCENARIO_COUNT * C.RATE_ENTRY_STRIDE <= C.DROP_RESOLVER_OFF);
check('weighted-drop table ends before the typed selection resolver',
  C.DROP_RESOLVER_OFF + dropResolverBytes.length <= C.DROP_TABLE_OFF &&
  C.DROP_TABLE_OFF + 8 + C.DROP_CLASS_COUNT * C.DROP_ENTRY_STRIDE <=
    C.TYPED_SELECTION_RESOLVER_OFF);
check('typed profiles occupy a bounded table before the direct rate resolver',
  C.TYPED_PROFILE_TABLE_OFF + 8 + C.TYPED_MAX_PROFILES *
    C.TYPED_PROFILE_ENTRY_STRIDE <= C.RATE_RESOLVER_OFF);
const messageTableProfiles = [
  Object.assign({}, customProfiles[0], { profileId: 1, terrainSlot: 2, label: 'Bandits!' }),
  Object.assign({}, customProfiles[0], { profileId: 2, terrainSlot: 3, label: 'Forest Raiders!' }),
  Object.assign({}, customProfiles[0], { profileId: 3, terrainSlot: 4, label: 'Bandits!' }),
];
const messageProfileTable = OB64.runtimeOverrides.buildTypedProfileTable(
  messageTableProfiles, rev0Layout);
const messagePointer0 = u32(messageProfileTable.bytes,
  8 + C.TYPED_MESSAGE_POINTER_OFF);
const messagePointer1 = u32(messageProfileTable.bytes,
  8 + C.TYPED_PROFILE_ENTRY_STRIDE + C.TYPED_MESSAGE_POINTER_OFF);
const messagePointer2 = u32(messageProfileTable.bytes,
  8 + C.TYPED_PROFILE_ENTRY_STRIDE * 2 + C.TYPED_MESSAGE_POINTER_OFF);
const messageStringOffset = messagePointer1 -
  (rev0Layout.MOD_BASE + C.TYPED_PROFILE_TABLE_OFF);
const messageStringBytes = [];
for (let cursor = messageStringOffset;
  cursor < messageProfileTable.bytes.length && messageProfileTable.bytes[cursor] !== 0;
  cursor++) messageStringBytes.push(messageProfileTable.bytes[cursor]);
check('typed profile text pointers deduplicate identical card text and retain unique text',
  messagePointer0 === messagePointer2 && messagePointer1 !== messagePointer0 &&
  String.fromCharCode(...messageStringBytes) === '@b@%0@n"Forest Raiders!"@a@c' &&
  messageProfileTable.bytes.length <= C.RATE_RESOLVER_OFF - C.TYPED_PROFILE_TABLE_OFF,
  JSON.stringify({ messagePointer0, messagePointer1, messagePointer2,
    tableBytes: messageProfileTable.bytes.length }));

function branchWordTarget(words, index) {
  const immediate = words[index] & 0xFFFF;
  const signed = immediate & 0x8000 ? immediate - 0x10000 : immediate;
  return index + 1 + signed;
}
function luiOriAddress(words, index) {
  return ((((words[index] & 0xFFFF) << 16) | (words[index + 1] & 0xFFFF)) >>> 0);
}
function hasLuiOriAddress(words, address) {
  for (let index = 0; index + 1 < words.length; index++) {
    if (luiOriAddress(words, index) === address) return true;
  }
  return false;
}
const zeroFallbackIndex = selectionResolverWords.findIndex(word =>
  (word & 0xFFFF0000) === 0x10400000);
const profilePointerCompareIndex = selectionResolverWords.findIndex(word =>
  (word & 0xFFFF0000) === 0x146D0000);
const profileExhaustedIndex = selectionResolverWords.findIndex(word =>
  (word & 0xFFFF0000) === 0x19600000);
const selectedReturnIndex = selectionResolverWords.indexOf(0x24420100);
const leaderClassLoadIndex = selectionResolverWords.findIndex(word =>
  word === OB64.squad._enc.lbu('v0', 16, 't2'));
const stagedClassStoreIndex = selectionResolverWords.findIndex(word =>
  word === OB64.squad._enc.sw('v0', 0, 't0'));
const matchTokenStoreIndex = selectionResolverWords.findIndex(word => word === 0xAD0E0008);
const matchSuccessBranchIndex = selectionResolverWords.findIndex((word, index) =>
  index > matchTokenStoreIndex && (word & 0xFFFF0000) === 0x10000000);
check('custom squad selection checks a matching profile before empty-slot fallback',
  profilePointerCompareIndex >= 0 && zeroFallbackIndex > profilePointerCompareIndex &&
  profileExhaustedIndex >= 0 &&
  branchWordTarget(selectionResolverWords, profileExhaustedIndex) === zeroFallbackIndex &&
  selectedReturnIndex === zeroFallbackIndex + 2 &&
  matchSuccessBranchIndex > matchTokenStoreIndex &&
  branchWordTarget(selectionResolverWords, matchSuccessBranchIndex) === selectedReturnIndex,
  JSON.stringify({ profilePointerCompareIndex, zeroFallbackIndex, profileExhaustedIndex,
    selectedReturnIndex, matchTokenStoreIndex, matchSuccessBranchIndex }));
check('custom squad selection stages the leader class before the neutral 0x100 marker',
  leaderClassLoadIndex > profilePointerCompareIndex &&
  stagedClassStoreIndex === leaderClassLoadIndex + 1 &&
  matchTokenStoreIndex > stagedClassStoreIndex &&
  selectedReturnIndex > matchTokenStoreIndex,
  JSON.stringify({ leaderClassLoadIndex, stagedClassStoreIndex,
    matchTokenStoreIndex, selectedReturnIndex }));
check('custom squad selection clears prior outcome and target state before matching',
  selectionResolverWords.includes(OB64.squad._enc.sw('zero', 24, 't0')) &&
  selectionResolverWords.includes(OB64.squad._enc.sw('zero', 28, 't0')));
const typedResolverWords = [
  selectionResolverWords,
  OB64.runtimeOverrides.buildMaterializerResolver(rev0Layout),
  OB64.runtimeOverrides.buildMessageResolver(rev0Layout),
  OB64.runtimeOverrides.buildPersuasionResolver(rev0Layout),
  OB64.runtimeOverrides.buildCleanupResolver(rev0Layout),
  OB64.runtimeOverrides.buildRetreatResolver(rev0Layout),
  OB64.runtimeOverrides.buildCycleBudgetResolver(rev0Layout),
  OB64.runtimeOverrides.buildRewardResolver(rev0Layout),
  OB64.runtimeOverrides.buildPersuasionTargetResolver(rev0Layout),
];
const roundContinuationResolverWords =
  OB64.runtimeOverrides.buildRoundContinuationResolver(rev0Layout);
const menuIteratorResolverWords =
  OB64.runtimeOverrides.buildMenuIteratorResolver(rev0Layout);
check('custom rounds satisfy only the native mode gate before native terminal checks',
  roundContinuationResolverWords.includes(OB64.squad._enc.jal(
    rev0Layout.ROUND_CONTINUATION_RETAIL_MODE_LIVE)) &&
  roundContinuationResolverWords.includes(OB64.squad._enc.lw('t1', 16, 't0')) &&
  roundContinuationResolverWords.includes(OB64.squad._enc.lw('t3', 20, 't0')) &&
  roundContinuationResolverWords.includes(OB64.squad._enc.ori(
    'v0', 'zero', 1)) &&
  roundContinuationResolverWords.includes(OB64.squad._enc.addiu(
    'sp', 'sp', -0x18)) &&
  roundContinuationResolverWords.includes(OB64.squad._enc.sw(
    'ra', 0x14, 'sp')) &&
  C.TYPED_MATERIALIZER_RESOLVER_OFF + typedResolverWords[1].length * 4 <=
    C.TYPED_ROUND_CONTINUATION_RESOLVER_OFF &&
  C.TYPED_ROUND_CONTINUATION_RESOLVER_OFF +
    roundContinuationResolverWords.length * 4 <= C.TYPED_MENU_ITERATOR_RESOLVER_OFF,
  JSON.stringify(roundContinuationResolverWords.map(word =>
    '0x' + word.toString(16).toUpperCase())));
check('command-menu iterator preserves retail progress and bounds padding recovery',
  menuIteratorResolverWords.includes(OB64.squad._enc.jal(
    rev0Layout.MENU_ITERATOR_RETAIL_LIVE)) &&
  menuIteratorResolverWords.includes(OB64.squad._enc.sw('a0', 0x10, 'sp')) &&
  menuIteratorResolverWords.includes(OB64.squad._enc.lui('t1', 0x801D)) &&
  menuIteratorResolverWords.includes(OB64.squad._enc.lw('t1', 0xE8C0, 't1')) &&
  menuIteratorResolverWords.includes(OB64.squad._enc.lw('t2', 0x814, 't1')) &&
  menuIteratorResolverWords.includes(OB64.squad._enc.lbu('t5', 0x10, 't4')) &&
  menuIteratorResolverWords.includes(OB64.squad._enc.ori('t6', 'zero', 0xFF)) &&
  menuIteratorResolverWords.includes(OB64.squad._enc.addiu('v0', 'v0', 1)) &&
  menuIteratorResolverWords.includes(OB64.squad._enc.addiu('v0', 'zero', -1)) &&
  C.TYPED_MENU_ITERATOR_RESOLVER_OFF + menuIteratorResolverWords.length * 4 <=
    C.TYPED_MESSAGE_RESOLVER_OFF,
  JSON.stringify(menuIteratorResolverWords.map(word =>
    '0x' + word.toString(16).toUpperCase())));
function recoverMenuPadding(opcodes, current, length) {
  for (let next = current + 1; next < length; next++) {
    const opcode = opcodes[next];
    if (opcode !== 0 && opcode !== 0xFF) return next;
  }
  return -1;
}
const trainingPadding = {};
trainingPadding[0x32] = 0;
trainingPadding[0x33] = 0x32;
check('Training first-extra-round fixture advances from 0x31 to the next real record',
  recoverMenuPadding(trainingPadding, 0x31, 0x95) === 0x33 &&
  recoverMenuPadding({ 4: 0xFF, 5: 0 }, 3, 6) === -1);
check('typed resolvers construct the exact scratch and profile-table addresses with LUI plus ORI',
  typedResolverWords.every(words =>
    hasLuiOriAddress(words, C.TYPED_SCRATCH_UNCACHED)) &&
  luiOriAddress(selectionResolverWords, 10) ===
    ((rev0Layout.MOD_BASE + C.TYPED_PROFILE_TABLE_OFF) >>> 0),
  JSON.stringify({
    scratch: typedResolverWords.map(words =>
      '0x' + luiOriAddress(words, 0).toString(16).toUpperCase()),
    profileTable: '0x' + luiOriAddress(selectionResolverWords, 10).toString(16).toUpperCase(),
  }));
const messageResolverWords = typedResolverWords[2];
const typedContinuationWords = OB64.runtimeOverrides.buildSharedContinuation(
  mixedPlan.blob.length,
  Object.assign({}, rev0Layout, { SENTINEL: C.NEUTRAL_SHARED_SENTINEL }), true);
const messageTextHook = mixedPlan.writes.find(write =>
  write.offset === rev0Layout.MESSAGE_TEXT_HOOK_ROM).bytes;
check('custom message resolver handles both card selection and runtime text pointers',
  messageResolverWords.filter(word => word === OB64.squad._enc.jr('ra')).length === 4 &&
  messageResolverWords.includes(OB64.squad._enc.lbu(
    't1', rev0Layout.MESSAGE_INDEX_HIGH_RAM & 0xFFFF, 't0')) &&
  messageResolverWords.includes(OB64.squad._enc.lbu(
    't1', rev0Layout.MESSAGE_INDEX_LOW_RAM & 0xFFFF, 't0')) &&
  messageResolverWords.includes(OB64.squad._enc.lw(
    'v1', C.TYPED_MESSAGE_POINTER_OFF, 't3')) &&
  !messageResolverWords.includes(OB64.squad._enc.j(rev0Layout.MESSAGE_CONTINUATION_LIVE)) &&
  rev0Layout.MESSAGE_CONTINUATION_LIVE === 0x801BACA0,
  JSON.stringify({
    returnCount: messageResolverWords.filter(word =>
      word === OB64.squad._enc.jr('ra')).length,
    mappedContinuation: '0x' + rev0Layout.MESSAGE_CONTINUATION_LIVE.toString(16).toUpperCase(),
  }));
check('message-text hook preserves retail offsets until the typed module is resident',
  typedContinuationWords.length * 4 <= 0xC0 &&
  u32(messageTextHook, 0) === OB64.squad._enc.jal(
    typedContinuationWords.messageTextStubRam) &&
  u32(messageTextHook, 4) === OB64.squad._enc.nop() &&
  typedContinuationWords[33] === OB64.squad._enc.lui('t0', 0xA040) &&
  typedContinuationWords.includes(OB64.squad._enc.j(
    (rev0Layout.MOD_BASE + C.TYPED_MESSAGE_RESOLVER_OFF) >>> 0)) &&
  typedContinuationWords.includes(OB64.squad._enc.addu('v1', 's0', 'v1')) &&
  typedContinuationWords.includes(OB64.squad._enc.sw('v1', 4, 'a0')),
  JSON.stringify({ continuationBytes: typedContinuationWords.length * 4,
    stub: typedContinuationWords.messageTextStubRam }));
const cleanupResolverWords = typedResolverWords[4];
const cleanupHook = mixedPlan.writes.find(write =>
  write.offset === rev0Layout.CLEANUP_HOOK_ROM).bytes;
check('retail cleanup remains intact until the later custom reward handler consumes context',
  cleanupResolverWords.filter(word => word === OB64.squad._enc.jr('ra')).length === 1 &&
  [8, 12, 16, 20, 24, 28].every(offset =>
    !cleanupResolverWords.includes(OB64.squad._enc.sw('zero', offset, 't0'))) &&
  cleanupResolverWords.includes(OB64.squad._enc.lui('v0', 0x801D)) &&
  cleanupResolverWords.includes(OB64.squad._enc.lw('v0', -0x1744, 'v0')) &&
  !cleanupResolverWords.includes(OB64.squad._enc.j(rev0Layout.CLEANUP_CONTINUATION_LIVE)) &&
  rev0Layout.LEGACY_CLEANUP_HOOK_ROM === 0x21BC40 &&
  rev0Layout.CLEANUP_HOOK_ROM === 0x21C044 &&
  rev0Layout.CLEANUP_CONTINUATION_LIVE === 0x801D8D7C &&
  equalBytes(cleanupHook, OB64.squad.wordsToBytes(C.CLEANUP_ORIGINAL_WORDS)),
  JSON.stringify({
    returnCount: cleanupResolverWords.filter(word =>
      word === OB64.squad._enc.jr('ra')).length,
    hookRom: '0x' + rev0Layout.CLEANUP_HOOK_ROM.toString(16).toUpperCase(),
    mappedContinuation: '0x' + rev0Layout.CLEANUP_CONTINUATION_LIVE.toString(16).toUpperCase(),
  }));

const retreatResolverWords = typedResolverWords[5];
check('custom retreat resolver compares the profile threshold with current HP percent',
  retreatResolverWords.includes(OB64.squad._enc.lbu('t2', 13, 't3')) &&
  retreatResolverWords.includes(OB64.squad._enc.lhu('v0', 0x20, 's0')) &&
  retreatResolverWords.includes(OB64.squad._enc.lhu('t1', 0x22, 's0')) &&
  retreatResolverWords.includes(OB64.squad._enc.divu('v1', 't1')) &&
  retreatResolverWords.includes(0x00001812) &&
  retreatResolverWords.includes(OB64.squad._enc.xori('v0', 'v0', 1)) &&
  retreatResolverWords.includes(OB64.squad._enc.j(rev0Layout.RETREAT_EPILOGUE_LIVE)),
  JSON.stringify(retreatResolverWords.map(word => '0x' + word.toString(16).toUpperCase())));

const cycleBudgetResolverWords = typedResolverWords[6];
check('custom Fight and Talk renew the post-action budget while retail keeps every decrement',
  cycleBudgetResolverWords.includes(OB64.squad._enc.ori('v0', 'zero', 2)) &&
  !cycleBudgetResolverWords.includes(OB64.squad._enc.ori('v0', 'zero', 3)) &&
  cycleBudgetResolverWords.includes(OB64.squad._enc.ori(
    't0', 'zero', C.TYPED_TALK_BUDGET_SELECTOR)) &&
  cycleBudgetResolverWords.includes(OB64.squad._enc.addiu('v0', 'v0', -1)) &&
  cycleBudgetResolverWords.includes(OB64.squad._enc.addiu('v0', 'v0', -2)) &&
  C.TYPED_RETREAT_RESOLVER_OFF + retreatResolverWords.length * 4 <=
    C.TYPED_CYCLE_BUDGET_RESOLVER_OFF &&
  C.TYPED_CYCLE_BUDGET_RESOLVER_OFF + cycleBudgetResolverWords.length * 4 <=
    C.TYPED_REWARD_RESOLVER_OFF);
const persuasionTargetResolverWords = typedResolverWords[8];
check('custom Talk outcomes reuse the exact persuasion target with a retail fallback',
  persuasionTargetResolverWords.includes(OB64.squad._enc.lw('v0', 28, 't0')) &&
  persuasionTargetResolverWords.includes(OB64.squad._enc.jr('ra')) &&
  persuasionTargetResolverWords.includes(OB64.squad._enc.j(
    rev0Layout.PERSUASION_TARGET_RETAIL_LIVE)) &&
  C.TYPED_PERSUASION_RESOLVER_OFF + typedResolverWords[3].length * 4 <=
    C.TYPED_PERSUASION_TARGET_RESOLVER_OFF &&
  C.TYPED_PERSUASION_TARGET_RESOLVER_OFF +
    persuasionTargetResolverWords.length * 4 <= C.TYPED_CLEANUP_RESOLVER_OFF);

const bootWords = OB64.runtimeOverrides.buildNeutralSharedBootstrap(mixedPlan.blob.length, rev0Layout);
const expectedDispatch = [
  C.SQUAD_RESOLVER_OFF, C.SHOP_RESOLVER_OFF, C.RATE_RESOLVER_OFF,
  C.RATE_RESOLVER_OFF, C.DROP_RESOLVER_OFF, C.TYPED_SELECTION_RESOLVER_OFF,
  C.TYPED_MATERIALIZER_RESOLVER_OFF, C.TYPED_MESSAGE_RESOLVER_OFF,
  C.TYPED_PERSUASION_RESOLVER_OFF, C.TYPED_MENU_ITERATOR_RESOLVER_OFF,
  C.TYPED_RETREAT_RESOLVER_OFF, C.TYPED_REWARD_RESOLVER_OFF,
].map(offset => (rev0Layout.MOD_BASE + offset) >>> 0);
check('neutral bootstrap fits the 108-byte cave and carries twelve dispatch pointers',
  bootWords.length * 4 <= 108 &&
  bootWords.slice(-expectedDispatch.length).join(',') === expectedDispatch.join(','),
  String(bootWords.length * 4));
check('mixed shared blob remains one PI-DMA transfer', mixedPlan.blob.length <= 0xFFFF,
  String(mixedPlan.blob.length));

const noTypedCapacityBlob = OB64.runtimeOverrides.buildNeutralSharedBlob({
  squadOverrides: Array.from({ length: 556 }, (_, index) => makeSquadOverride(index)),
  shopOverrides, shopCount: 256,
  scenarioRateOverrides: scenarioRates,
  weightedDropOverrides: weightedOverrides,
}, Object.assign({}, rev0Layout, { SENTINEL: C.NEUTRAL_SHARED_SENTINEL }));
check('all 556 retail squad rows still fit when typed profiles are absent',
  noTypedCapacityBlob.length <= 0xFFFF, String(noTypedCapacityBlob.length));

console.log('\n-- two-mode isolation and scenario-alias independence --');
const rateTable = OB64.runtimeOverrides.buildRateTable(scenarioRates);
function rateRow(key) { return 8 + key * C.RATE_ENTRY_STRIDE; }
const rowA = rateRow(scenarioA.runtimeKey);
const rowB = rateRow(scenarioB.runtimeKey);
check('shared-slice scenarios own different direct table rows',
  scenarioA.slice === scenarioB.slice && rowA !== rowB);
check('scenario A normal and alternate modes occupy separate eight-byte branches',
  rateTable[rowA] === 1 && u16(rateTable, rowA + 2) === 100 &&
  u32(rateTable, rowA + 4) === 72000 && rateTable[rowA + 8] === 2);
check('scenario B modes do not trample scenario A or each other',
  rateTable[rowB] === 2 && rateTable[rowB + 8] === 1 &&
  u16(rateTable, rowB + 10) === 6 && u32(rateTable, rowB + 12) === 1000 &&
  rateTable[rowA] === 1 && rateTable[rowA + 8] === 2);

const globalAndDirectZ64 = masterZ64.slice();
const changedGlobalRate = OB64.parseNeutralGlobalRate(globalAndDirectZ64);
changedGlobalRate.modified = true;
changedGlobalRate.linked = false;
changedGlobalRate.divisor = 72000;
changedGlobalRate.normalPassCount = 153;
changedGlobalRate.alternatePassCount = 11;
OB64.serializeNeutralGlobalRate(changedGlobalRate, globalAndDirectZ64);
const directOverGlobal = [{
  runtimeKey: scenarioA.runtimeKey,
  normal: { mode: 'override', passCount: 307, divisor: 72000 },
  alternate: { mode: 'inherit', passCount: null, divisor: null },
}];
const globalAndDirectRom = makeRom(rev0, globalAndDirectZ64);
globalAndDirectRom.neutralEncounters = { globalRate: changedGlobalRate };
const globalAndDirectPlan = OB64.runtimeOverrides.buildRuntimeOverrideWrites(
  [], [], 256, globalAndDirectRom, {
    scenarioRateOverrides: directOverGlobal,
    weightedDropOverrides: [],
    customNeutralSquads: [],
  }
);
applyWrites(globalAndDirectZ64, globalAndDirectPlan);
const globalAndDirectOwners = OB64.consumableEffects.standardPatchOwners(
  globalAndDirectRom, { encounters: true }
).concat([{
  id: 'runtime-overrides',
  name: 'Shared Runtime Overrides',
  category: 'runtimeOverrides',
  regions: OB64.runtimeOverrides.patchRegions(globalAndDirectRom),
}]);
const globalAndDirectConflicts = OB64.consumableEffects.findRegionConflicts(
  globalAndDirectOwners
);
const reparsedGlobalRate = OB64.parseNeutralGlobalRate(globalAndDirectZ64);
const reparsedDirectRate = OB64.runtimeOverrides.parseScenarioRateOverrides(
  globalAndDirectZ64, globalAndDirectRom
);
check('global fallback and direct scenario override own disjoint patch words',
  globalAndDirectConflicts.length === 0, JSON.stringify(globalAndDirectConflicts));
check('global fallback survives beside the direct scenario hook',
  reparsedGlobalRate.normalPassCount === 153 &&
  reparsedGlobalRate.alternatePassCount === 11 &&
  reparsedGlobalRate.divisor === 72000, JSON.stringify(reparsedGlobalRate));
check('direct scenario rate remains distinct and therefore takes precedence',
  JSON.stringify(reparsedDirectRate) === JSON.stringify(directOverGlobal),
  JSON.stringify(reparsedDirectRate));

console.log('\n-- semantic readback, per-profile message text, and persuasion --');
const mixedCandidate = masterZ64.slice();
applyWrites(mixedCandidate, mixedPlan);
const candidateRom = makeRom(rev0, mixedCandidate);
const parsedRates = OB64.runtimeOverrides.parseScenarioRateOverrides(mixedCandidate, candidateRom);
const parsedWeights = OB64.runtimeOverrides.parseWeightedDropOverrides(mixedCandidate, candidateRom);
const parsedProfiles = OB64.runtimeOverrides.parseCustomNeutralSquads(mixedCandidate, candidateRom);
const parsedShops = OB64.runtimeOverrides.parseShopOverrides(mixedCandidate, candidateRom);
check('both direct scenario rows preserve independent normal and alternate modes',
  JSON.stringify(parsedRates) === JSON.stringify(scenarioRates), JSON.stringify(parsedRates));
check('weighted readback preserves all three class-slot weights',
  JSON.stringify(parsedWeights) === JSON.stringify(weightedOverrides), JSON.stringify(parsedWeights));
check('shop semantic readback survives inside the OBMB blob',
  parsedShops[2] && JSON.stringify(parsedShops[2].items) === '[1,2]' &&
  JSON.stringify(parsedShops[2].consumables) === '[1,8]');
check('typed profile readback preserves native cells zero and eight plus all authored fields',
  parsedProfiles.length === 1 && parsedProfiles[0].runtimeKey === scenarioA.runtimeKey &&
  parsedProfiles[0].slice === scenarioA.slice && parsedProfiles[0].terrainSlot === 2 &&
  JSON.stringify(parsedProfiles[0].members) === JSON.stringify(customMembersFixture()) &&
  parsedProfiles[0].members.some(member => member.cell === 0) &&
  parsedProfiles[0].members.some(member => member.cell === 8) &&
  JSON.stringify(parsedProfiles[0].equipment) === JSON.stringify(customEquipmentFixture()) &&
  parsedProfiles[0].label === 'Bandits!' &&
  parsedProfiles[0].persuasion.mode === 'fixed' && parsedProfiles[0].persuasion.chance === 37 &&
  JSON.stringify(parsedProfiles[0].persuasion.classBonuses) ===
    JSON.stringify(customBonusesFixture()) &&
  parsedProfiles[0].retreat.hpThreshold === 25 &&
  JSON.stringify(parsedProfiles[0].rewards) === JSON.stringify(customRewardsFixture()),
  JSON.stringify(parsedProfiles));

const priorTypedCandidate = mixedCandidate.slice();
const priorTypedProfileBase = rev0Layout.TAIL_Z64 + C.TYPED_PROFILE_TABLE_OFF;
priorTypedCandidate[priorTypedProfileBase + 4] = C.PREVIOUS_TYPED_PROFILE_VERSION - 1;
check('pre-v4 custom profile tables are rejected instead of translating 1-9 cells',
  OB64.runtimeOverrides.parseCustomNeutralSquads(
    priorTypedCandidate, makeRom(rev0, priorTypedCandidate)).length === 0);
const v4TypedCandidate = mixedCandidate.slice();
v4TypedCandidate[priorTypedProfileBase + 4] = C.PREVIOUS_TYPED_PROFILE_VERSION;
v4TypedCandidate.fill(0, priorTypedProfileBase + 8 + C.TYPED_MESSAGE_POINTER_OFF,
  priorTypedProfileBase + 8 + C.TYPED_MESSAGE_POINTER_OFF + 4);
v4TypedCandidate.set(OB64.squad.wordsToBytes([
  C.OBMA_NEUTRAL_SHARED_SENTINEL,
]), rev0Layout.TAIL_Z64);
const parsedV4Profiles = OB64.runtimeOverrides.parseCustomNeutralSquads(
  v4TypedCandidate, makeRom(rev0, v4TypedCandidate));
check('OBMA v4 profiles upgrade with their fixed Bandits encounter text',
  parsedV4Profiles.length === 1 && parsedV4Profiles[0].label === 'Bandits!');
const previousSentinelCandidate = mixedCandidate.slice();
previousSentinelCandidate.set(OB64.squad.wordsToBytes([
  C.PREVIOUS_NEUTRAL_SHARED_SENTINEL,
]), rev0Layout.TAIL_Z64);
previousSentinelCandidate.set(OB64.squad.wordsToBytes(
  C.MENU_ITERATOR_ORIGINAL_WORDS), rev0Layout.MENU_ITERATOR_HOOK_ROM);
const previousSentinelRom = makeRom(rev0, previousSentinelCandidate);
const obm6SentinelCandidate = mixedCandidate.slice();
obm6SentinelCandidate.set(OB64.squad.wordsToBytes([
  C.OBM6_NEUTRAL_SHARED_SENTINEL,
]), rev0Layout.TAIL_Z64);
obm6SentinelCandidate.set(OB64.squad.wordsToBytes(
  C.MENU_ITERATOR_ORIGINAL_WORDS), rev0Layout.MENU_ITERATOR_HOOK_ROM);
const obm6SentinelRom = makeRom(rev0, obm6SentinelCandidate);
const obm7SentinelCandidate = mixedCandidate.slice();
obm7SentinelCandidate.set(OB64.squad.wordsToBytes([
  C.OBM7_NEUTRAL_SHARED_SENTINEL,
]), rev0Layout.TAIL_Z64);
obm7SentinelCandidate.set(OB64.squad.wordsToBytes(
  C.MENU_ITERATOR_ORIGINAL_WORDS), rev0Layout.MENU_ITERATOR_HOOK_ROM);
obm7SentinelCandidate.set(OB64.squad.wordsToBytes(
  C.ROUND_CONTINUATION_ORIGINAL_WORDS), rev0Layout.ROUND_CONTINUATION_HOOK_ROM);
const obm7SentinelRom = makeRom(rev0, obm7SentinelCandidate);
const obm8SentinelCandidate = mixedCandidate.slice();
obm8SentinelCandidate.set(OB64.squad.wordsToBytes([
  C.OBM8_NEUTRAL_SHARED_SENTINEL,
]), rev0Layout.TAIL_Z64);
obm8SentinelCandidate.set(OB64.squad.wordsToBytes(
  C.MENU_ITERATOR_ORIGINAL_WORDS), rev0Layout.MENU_ITERATOR_HOOK_ROM);
obm8SentinelCandidate.set(OB64.squad.wordsToBytes(
  C.ROUND_CONTINUATION_ORIGINAL_WORDS), rev0Layout.ROUND_CONTINUATION_HOOK_ROM);
obm8SentinelCandidate.set(OB64.squad.wordsToBytes([
  OB64.squad._enc.jal(
    (rev0Layout.MOD_BASE + C.TYPED_ROUND_CONTINUATION_RESOLVER_OFF) >>> 0),
  OB64.squad._enc.nop(),
]), rev0Layout.LEGACY_ROUND_CONTINUATION_HOOK_ROM);
const obm8SentinelRom = makeRom(rev0, obm8SentinelCandidate);
const obm9SentinelCandidate = mixedCandidate.slice();
obm9SentinelCandidate.set(OB64.squad.wordsToBytes([
  C.OBM9_NEUTRAL_SHARED_SENTINEL,
]), rev0Layout.TAIL_Z64);
obm9SentinelCandidate.set(OB64.squad.wordsToBytes(
  C.MENU_ITERATOR_ORIGINAL_WORDS), rev0Layout.MENU_ITERATOR_HOOK_ROM);
const obm9SentinelRom = makeRom(rev0, obm9SentinelCandidate);
check('existing OBM5 through OBM9 exports remain readable after the OBMB code bump',
  JSON.stringify(OB64.runtimeOverrides.parseScenarioRateOverrides(
    previousSentinelCandidate, previousSentinelRom)) === JSON.stringify(parsedRates) &&
  JSON.stringify(OB64.runtimeOverrides.parseWeightedDropOverrides(
    previousSentinelCandidate, previousSentinelRom)) === JSON.stringify(parsedWeights) &&
  JSON.stringify(OB64.runtimeOverrides.parseCustomNeutralSquads(
    previousSentinelCandidate, previousSentinelRom)) === JSON.stringify(parsedProfiles) &&
  JSON.stringify(OB64.runtimeOverrides.parseScenarioRateOverrides(
    obm6SentinelCandidate, obm6SentinelRom)) === JSON.stringify(parsedRates) &&
  JSON.stringify(OB64.runtimeOverrides.parseWeightedDropOverrides(
    obm6SentinelCandidate, obm6SentinelRom)) === JSON.stringify(parsedWeights) &&
  JSON.stringify(OB64.runtimeOverrides.parseCustomNeutralSquads(
    obm6SentinelCandidate, obm6SentinelRom)) === JSON.stringify(parsedProfiles) &&
  JSON.stringify(OB64.runtimeOverrides.parseScenarioRateOverrides(
    obm7SentinelCandidate, obm7SentinelRom)) === JSON.stringify(parsedRates) &&
  JSON.stringify(OB64.runtimeOverrides.parseWeightedDropOverrides(
    obm7SentinelCandidate, obm7SentinelRom)) === JSON.stringify(parsedWeights) &&
  JSON.stringify(OB64.runtimeOverrides.parseCustomNeutralSquads(
    obm7SentinelCandidate, obm7SentinelRom)) === JSON.stringify(parsedProfiles) &&
  JSON.stringify(OB64.runtimeOverrides.parseScenarioRateOverrides(
    obm8SentinelCandidate, obm8SentinelRom)) === JSON.stringify(parsedRates) &&
  JSON.stringify(OB64.runtimeOverrides.parseWeightedDropOverrides(
    obm8SentinelCandidate, obm8SentinelRom)) === JSON.stringify(parsedWeights) &&
  JSON.stringify(OB64.runtimeOverrides.parseCustomNeutralSquads(
    obm8SentinelCandidate, obm8SentinelRom)) === JSON.stringify(parsedProfiles) &&
  JSON.stringify(OB64.runtimeOverrides.parseScenarioRateOverrides(
    obm9SentinelCandidate, obm9SentinelRom)) === JSON.stringify(parsedRates) &&
  JSON.stringify(OB64.runtimeOverrides.parseWeightedDropOverrides(
    obm9SentinelCandidate, obm9SentinelRom)) === JSON.stringify(parsedWeights) &&
  JSON.stringify(OB64.runtimeOverrides.parseCustomNeutralSquads(
    obm9SentinelCandidate, obm9SentinelRom)) === JSON.stringify(parsedProfiles));
const obm6UpgradeSource = obm6SentinelCandidate.slice();
obm6UpgradeSource.set(OB64.squad.wordsToBytes(C.FIGHT_BUDGET_ORIGINAL_WORDS),
  rev0Layout.FIGHT_RESULT_BUDGET_HOOK_ROM);
const obm6UpgradePlan = OB64.runtimeOverrides.buildRuntimeOverrideWrites(
  oneSquad, shopOverrides, 256, makeRom(rev0, obm6UpgradeSource), {
    scenarioRateOverrides: scenarioRates,
    weightedDropOverrides: weightedOverrides,
    customNeutralSquads: customProfiles,
  }
);
const obm6UpgradeFightResult = obm6UpgradePlan.writes.find(write =>
  write.offset === rev0Layout.FIGHT_RESULT_BUDGET_HOOK_ROM);
check('an OBM6 source upgrades the missing Fight-result hook and runtime sentinel',
  obm6UpgradePlan.sentinel === C.NEUTRAL_SHARED_SENTINEL &&
  obm6UpgradeFightResult &&
  u32(obm6UpgradeFightResult.bytes, 0) === OB64.squad._enc.jal(
    (rev0Layout.MOD_BASE + C.TYPED_CYCLE_BUDGET_RESOLVER_OFF) >>> 0) &&
  u32(obm6UpgradeFightResult.bytes, 4) === OB64.squad._enc.ori(
    't9', 'zero', C.TYPED_FIGHT_BUDGET_SELECTOR));
const obm7UpgradePlan = OB64.runtimeOverrides.buildRuntimeOverrideWrites(
  oneSquad, shopOverrides, 256, obm7SentinelRom, {
    scenarioRateOverrides: scenarioRates,
    weightedDropOverrides: weightedOverrides,
    customNeutralSquads: customProfiles,
  }
);
const obm7UpgradeRoundContinuation = obm7UpgradePlan.writes.find(write =>
  write.offset === rev0Layout.ROUND_CONTINUATION_HOOK_ROM);
check('an OBM7 source installs the native round-gate hook and OBMB sentinel',
  obm7UpgradePlan.sentinel === C.NEUTRAL_SHARED_SENTINEL &&
  obm7UpgradeRoundContinuation &&
  u32(obm7UpgradeRoundContinuation.bytes, 0) === OB64.squad._enc.jal(
    (rev0Layout.MOD_BASE + C.TYPED_ROUND_CONTINUATION_RESOLVER_OFF) >>> 0) &&
  u32(obm7UpgradeRoundContinuation.bytes, 4) === OB64.squad._enc.nop());
const obm8UpgradePlan = OB64.runtimeOverrides.buildRuntimeOverrideWrites(
  oneSquad, shopOverrides, 256, obm8SentinelRom, {
    scenarioRateOverrides: scenarioRates,
    weightedDropOverrides: weightedOverrides,
    customNeutralSquads: customProfiles,
  }
);
const obm8UpgradeRoundGate = obm8UpgradePlan.writes.find(write =>
  write.offset === rev0Layout.ROUND_CONTINUATION_HOOK_ROM);
const obm8UpgradeLegacyRound = obm8UpgradePlan.writes.find(write =>
  write.offset === rev0Layout.LEGACY_ROUND_CONTINUATION_HOOK_ROM);
check('an OBM8 source moves continuation from the terminal writer to the native round gate',
  obm8UpgradePlan.sentinel === C.NEUTRAL_SHARED_SENTINEL &&
  obm8UpgradeRoundGate && obm8UpgradeLegacyRound &&
  u32(obm8UpgradeRoundGate.bytes, 0) === OB64.squad._enc.jal(
    (rev0Layout.MOD_BASE + C.TYPED_ROUND_CONTINUATION_RESOLVER_OFF) >>> 0) &&
  u32(obm8UpgradeLegacyRound.bytes, 0) ===
    C.LEGACY_ROUND_CONTINUATION_ORIGINAL_WORDS[0] &&
  u32(obm8UpgradeLegacyRound.bytes, 4) ===
    C.LEGACY_ROUND_CONTINUATION_ORIGINAL_WORDS[1]);
const obm9UpgradePlan = OB64.runtimeOverrides.buildRuntimeOverrideWrites(
  oneSquad, shopOverrides, 256, obm9SentinelRom, {
    scenarioRateOverrides: scenarioRates,
    weightedDropOverrides: weightedOverrides,
    customNeutralSquads: customProfiles,
  }
);
const obm9UpgradeMenuIterator = obm9UpgradePlan.writes.find(write =>
  write.offset === rev0Layout.MENU_ITERATOR_HOOK_ROM);
check('an OBM9 source installs the scoped command-menu iterator and OBMB sentinel',
  obm9UpgradePlan.sentinel === C.NEUTRAL_SHARED_SENTINEL &&
  obm9UpgradeMenuIterator &&
  u32(obm9UpgradeMenuIterator.bytes, 0) === OB64.squad._enc.jal(
    rev0Layout.BOOT_RAM) &&
  u32(obm9UpgradeMenuIterator.bytes, 4) === OB64.squad._enc.ori(
    't9', 'zero', C.TYPED_MENU_ITERATOR_DISPATCH_ID));
check('new custom text leaves retail MESWIN entry 15 empty',
  OB64.runtimeOverrides.buildBanditsMessageArchiveWrite(mixedCandidate, false) === null &&
  OB64.runtimeOverrides.buildBanditsMessageArchiveWrite(mixedCandidate, true) !== null);

const persuasionWords = OB64.runtimeOverrides.buildPersuasionResolver(rev0Layout);
const persuasionEpilogueJump = OB64.squad._enc.j(rev0Layout.PERSUASION_EPILOGUE_LIVE);
const persuasionExitIndexes = persuasionWords.reduce((out, word, index) => {
  if (word === persuasionEpilogueJump) out.push(index);
  return out;
}, []);
check('custom persuasion reports success as result zero and failure as non-retreat result two',
  persuasionExitIndexes.some(index =>
    persuasionWords[index - 2] === OB64.squad._enc.addu('v0', 'zero', 'zero') &&
    persuasionWords[index - 1] === OB64.squad._enc.addiu('sp', 'sp', 0x20)) &&
  persuasionExitIndexes.some(index =>
    persuasionWords[index - 2] === OB64.squad._enc.ori('v0', 'zero', 2) &&
    persuasionWords[index - 1] === OB64.squad._enc.addiu('sp', 'sp', 0x20)) &&
  !persuasionWords.includes(OB64.squad._enc.ori('v0', 'zero', 1)) &&
  persuasionWords.includes(OB64.squad._enc.sw('s0', 28, 't0')) &&
  persuasionWords.includes(OB64.squad._enc.jal(rev0Layout.PERSUASION_ACTOR_AT_INDEX_LIVE)) &&
  persuasionWords.includes(OB64.squad._enc.jal(rev0Layout.PERSUASION_FILTER_A_LIVE)) &&
  persuasionWords.includes(OB64.squad._enc.jal(rev0Layout.PERSUASION_FILTER_B_LIVE)) &&
  persuasionWords.includes(OB64.squad._enc.jal(rev0Layout.PERSUASION_FILTER_C_LIVE)) &&
  persuasionWords.includes(OB64.squad._enc.jal(rev0Layout.PERSUASION_FILTER_D_LIVE)) &&
  persuasionWords.includes(OB64.squad._enc.jal(rev0Layout.PERSUASION_ELIGIBLE_LIVE)) &&
  persuasionWords.includes(OB64.squad._enc.jal(rev0Layout.PERSUASION_RNG_LIVE)) &&
  persuasionWords.includes(OB64.squad._enc.jal(rev0Layout.PERSUASION_RETAIL_HELPER_LIVE)));
check('persuasion helper calls preserve the o32 argument-home area',
  persuasionWords.includes(OB64.squad._enc.addiu('sp', 'sp', -0x20)) &&
  persuasionWords.includes(OB64.squad._enc.sw('t3', 0x10, 'sp')) &&
  persuasionWords.includes(OB64.squad._enc.sw('v0', 0x14, 'sp')) &&
  persuasionWords.includes(OB64.squad._enc.sw('t2', 0x18, 'sp')) &&
  persuasionWords.includes(OB64.squad._enc.sw('ra', 0x1C, 'sp')) &&
  !persuasionWords.includes(OB64.squad._enc.addiu('sp', 'sp', -8)));
check('custom persuasion reads the current player leader class and caps one bonus at 100',
  persuasionWords.includes(OB64.squad._enc.lbu('t4', 0x4B, 's2')) &&
  persuasionWords.includes(OB64.squad._enc.ori('t6', 'zero', 3)) &&
  persuasionWords.includes(OB64.squad._enc.ori('t1', 'zero', 100)));
const persuasionHook = mixedPlan.writes.find(write =>
  write.offset === rev0Layout.PERSUASION_HOOK_ROM).bytes;
check('persuasion hook preserves retail eligibility and dispatches only the final custom roll',
  (u32(persuasionHook, 0) >>> 26) === 3 &&
  u32(persuasionHook, 4) === OB64.squad._enc.ori('t9', 'zero', 8));
const persuasionTargetHookWrites = rev0Layout.PERSUASION_TARGET_HOOK_ROMS.map(offset =>
  mixedPlan.writes.find(write => write.offset === offset));
const persuasionRecruitTargetHookWrite = mixedPlan.writes.find(write =>
  write.offset === rev0Layout.PERSUASION_RECRUIT_TARGET_HOOK_ROM);
check('Talk presentation and recruitment reuse the exact selected target',
  persuasionTargetHookWrites.every(write => write &&
    u32(write.bytes, 0) === OB64.squad._enc.jal(
      (rev0Layout.MOD_BASE + C.TYPED_PERSUASION_TARGET_RESOLVER_OFF) >>> 0) &&
    u32(write.bytes, 4) === OB64.squad._enc.nop()) &&
  persuasionRecruitTargetHookWrite &&
  u32(persuasionRecruitTargetHookWrite.bytes, 0) === OB64.squad._enc.jal(
    (rev0Layout.MOD_BASE + C.TYPED_PERSUASION_TARGET_RESOLVER_OFF) >>> 0) &&
  u32(persuasionRecruitTargetHookWrite.bytes, 4) ===
    C.PERSUASION_RECRUIT_TARGET_ORIGINAL_WORDS[1]);
const retreatHook = mixedPlan.writes.find(write =>
  write.offset === rev0Layout.RETREAT_HOOK_ROM).bytes;
check('retreat hook preserves retail eligibility and dispatches only the custom threshold',
  (u32(retreatHook, 0) >>> 26) === 3 &&
  u32(retreatHook, 4) === OB64.squad._enc.ori('t9', 'zero', 10));
const fightBudgetHook = mixedPlan.writes.find(write =>
  write.offset === rev0Layout.FIGHT_BUDGET_HOOK_ROM).bytes;
const talkBudgetHook = mixedPlan.writes.find(write =>
  write.offset === rev0Layout.TALK_BUDGET_HOOK_ROM).bytes;
const fightResultBudgetHook = mixedPlan.writes.find(write =>
  write.offset === rev0Layout.FIGHT_RESULT_BUDGET_HOOK_ROM).bytes;
const roundContinuationHook = mixedPlan.writes.find(write =>
  write.offset === rev0Layout.ROUND_CONTINUATION_HOOK_ROM).bytes;
const menuIteratorHook = mixedPlan.writes.find(write =>
  write.offset === rev0Layout.MENU_ITERATOR_HOOK_ROM).bytes;
check('all cycle-budget hooks call the loaded tail resolver with the correct selector',
  u32(fightBudgetHook, 0) === OB64.squad._enc.jal(
    (rev0Layout.MOD_BASE + C.TYPED_CYCLE_BUDGET_RESOLVER_OFF) >>> 0) &&
  u32(fightBudgetHook, 4) === OB64.squad._enc.ori(
    't9', 'zero', C.TYPED_FIGHT_BUDGET_SELECTOR) &&
  u32(talkBudgetHook, 0) === OB64.squad._enc.jal(
    (rev0Layout.MOD_BASE + C.TYPED_CYCLE_BUDGET_RESOLVER_OFF) >>> 0) &&
  u32(talkBudgetHook, 4) === OB64.squad._enc.ori(
    't9', 'zero', C.TYPED_TALK_BUDGET_SELECTOR) &&
  u32(fightResultBudgetHook, 0) === OB64.squad._enc.jal(
    (rev0Layout.MOD_BASE + C.TYPED_CYCLE_BUDGET_RESOLVER_OFF) >>> 0) &&
  u32(fightResultBudgetHook, 4) === OB64.squad._enc.ori(
    't9', 'zero', C.TYPED_FIGHT_BUDGET_SELECTOR));
check('round completion calls the loaded living-side resolver and preserves its exact return',
  u32(roundContinuationHook, 0) === OB64.squad._enc.jal(
    (rev0Layout.MOD_BASE + C.TYPED_ROUND_CONTINUATION_RESOLVER_OFF) >>> 0) &&
  u32(roundContinuationHook, 4) === OB64.squad._enc.nop());
check('command-menu scan loads the shared module and selects only padding recovery',
  u32(menuIteratorHook, 0) === OB64.squad._enc.jal(rev0Layout.BOOT_RAM) &&
  u32(menuIteratorHook, 4) === OB64.squad._enc.ori(
    't9', 'zero', C.TYPED_MENU_ITERATOR_DISPATCH_ID));
const rewardWords = OB64.runtimeOverrides.buildRewardResolver(rev0Layout);
const rewardHook = mixedPlan.writes.find(write =>
  write.offset === rev0Layout.REWARD_HOOK_ROM).bytes;
check('custom reward resolver performs one weighted roll and suppresses persuasion rewards',
  rewardWords.includes(OB64.squad._enc.lw('t4', 24, 't0')) &&
  rewardWords.includes(OB64.squad._enc.lhu('s3', 0, 't6')) &&
  [8, 12, 16, 20, 24, 28].every(offset =>
    rewardWords.includes(OB64.squad._enc.sw('zero', offset, 't0'))) &&
  rewardWords.indexOf(OB64.squad._enc.sw('zero', 16, 't0')) >
    rewardWords.indexOf(OB64.squad._enc.sw('zero', 28, 't0')) &&
  !rewardWords.includes(OB64.squad._enc.sw('t4', 24, 't0')) &&
  rewardWords.includes(OB64.squad._enc.addiu('sp', 'sp', -0x20)) &&
  rewardWords.includes(OB64.squad._enc.sw('ra', 0x1C, 'sp')) &&
  rewardWords.filter(word => word ===
    OB64.squad._enc.lbu('v0', 0x3670, 'v0')).length === 2);
const dynamicRewardReturns = rewardWords.reduce((count, word, index) =>
  count + (word === OB64.squad._enc.addiu(
    't7', 'ra', C.REWARD_CONTINUATION_FROM_RA) &&
    rewardWords[index + 1] === OB64.squad._enc.jr('t7') &&
    rewardWords[index + 2] === OB64.squad._enc.nop() ? 1 : 0), 0);
check('custom and retail reward paths resume from the live hook return address',
  C.REWARD_CONTINUATION_FROM_RA === 0x18 &&
  dynamicRewardReturns === 2 &&
  !rewardWords.includes(OB64.squad._enc.j(0x801720D4)));
check('reward hook dispatches through client eleven',
  (u32(rewardHook, 0) >>> 26) === 3 &&
  u32(rewardHook, 4) === OB64.squad._enc.ori('t9', 'zero', 11));

const restored = mixedCandidate.slice();
OB64.runtimeOverrides.restoreAll(restored, makeRom(rev0, restored));
const restoredRegions = OB64.runtimeOverrides.patchRegions(makeRom(rev0, restored))
  .filter(region => region.kind === 'rom');
const byteExactRestoreRegions = restoredRegions.filter(region =>
  region.label.indexOf('MESWIN archive') === -1);
check('removing the last shared override restores every code and runtime-data region exactly',
  byteExactRestoreRegions.every(region => equalBytes(
    restored.subarray(region.start, region.start + region.size),
    masterZ64.subarray(region.start, region.start + region.size)
  )), JSON.stringify(restoredRegions));
const restoredArchives = OB64.findArchives(restored);
const retailArchives = OB64.findArchives(masterZ64);
check('message removal restores the empty entry while preserving following archive offsets',
  OB64.runtimeOverrides.buildBanditsMessageArchiveWrite(restored, false) === null &&
  restoredArchives[815].offset === retailArchives[815].offset &&
  restoredArchives[816].offset === retailArchives[816].offset);

const foreignTypedRom = makeRom(rev0);
foreignTypedRom.z64[rev0Layout.SELECTION_HOOK_ROM] ^= 1;
throws('custom squad composer refuses a foreign typed-selection hook', () =>
  OB64.runtimeOverrides.buildRuntimeOverrideWrites([], [], 256, foreignTypedRom, {
    scenarioRateOverrides: [], weightedDropOverrides: [], customNeutralSquads: customProfiles,
  }), /unrecognized bytes/i);
const foreignRoundContinuationRom = makeRom(rev0);
foreignRoundContinuationRom.z64[rev0Layout.ROUND_CONTINUATION_HOOK_ROM] ^= 1;
throws('custom squad composer refuses a foreign round-continuation hook', () =>
  OB64.runtimeOverrides.buildRuntimeOverrideWrites([], [], 256,
    foreignRoundContinuationRom, {
      scenarioRateOverrides: [], weightedDropOverrides: [],
      customNeutralSquads: customProfiles,
    }), /unrecognized bytes/i);
const foreignMenuIteratorRom = makeRom(rev0);
foreignMenuIteratorRom.z64[rev0Layout.MENU_ITERATOR_HOOK_ROM] ^= 1;
throws('custom squad composer refuses a foreign command-menu iterator hook', () =>
  OB64.runtimeOverrides.buildRuntimeOverrideWrites([], [], 256,
    foreignMenuIteratorRom, {
      scenarioRateOverrides: [], weightedDropOverrides: [],
      customNeutralSquads: customProfiles,
    }), /unrecognized bytes/i);
const foreignPersuasionTargetRom = makeRom(rev0);
foreignPersuasionTargetRom.z64[rev0Layout.PERSUASION_TARGET_HOOK_ROMS[0]] ^= 1;
throws('custom squad composer refuses a foreign persuasion-target hook', () =>
  OB64.runtimeOverrides.buildRuntimeOverrideWrites([], [], 256,
    foreignPersuasionTargetRom, {
      scenarioRateOverrides: [], weightedDropOverrides: [],
      customNeutralSquads: customProfiles,
    }), /unrecognized bytes/i);

const preEligibilityRom = makeRom(rev0);
preEligibilityRom.z64.set(OB64.squad.wordsToBytes([
  OB64.squad._enc.j((rev0Layout.CACHE_CONT_RAM + 33 * 4) >>> 0),
  OB64.squad._enc.nop(),
]), C.PRE_ELIGIBILITY_PERSUASION_HOOK_ROM);
const persuasionUpgradePlan = OB64.runtimeOverrides.buildRuntimeOverrideWrites(
  [], [], 256, preEligibilityRom, {
    scenarioRateOverrides: [], weightedDropOverrides: [],
    customNeutralSquads: customProfiles,
  }
);
const persuasionUpgradeWrite = persuasionUpgradePlan.writes.find(write =>
  write.offset === C.PRE_ELIGIBILITY_PERSUASION_HOOK_ROM);
check('a prior pre-eligibility persuasion hook is restored during upgrade',
  persuasionUpgradeWrite && equalBytes(persuasionUpgradeWrite.bytes,
    OB64.squad.wordsToBytes(C.PRE_ELIGIBILITY_PERSUASION_ORIGINAL_WORDS)));

const prematureCleanupRom = makeRom(rev0);
prematureCleanupRom.z64.set(OB64.squad.wordsToBytes([
  OB64.squad._enc.jal(rev0Layout.BOOT_RAM),
  OB64.squad._enc.ori('t9', 'zero', 9),
]), rev0Layout.LEGACY_CLEANUP_HOOK_ROM);
prematureCleanupRom.z64.set(OB64.squad.wordsToBytes([
  OB64.squad._enc.jal(
    (rev0Layout.MOD_BASE + C.TYPED_CLEANUP_RESOLVER_OFF) >>> 0),
  OB64.squad._enc.nop(),
]), rev0Layout.CLEANUP_HOOK_ROM);
const cleanupUpgradePlan = OB64.runtimeOverrides.buildRuntimeOverrideWrites(
  [], [], 256, prematureCleanupRom, {
    scenarioRateOverrides: [], weightedDropOverrides: [],
    customNeutralSquads: customProfiles,
  }
);
const prematureCleanupRestore = cleanupUpgradePlan.writes.find(write =>
  write.offset === rev0Layout.LEGACY_CLEANUP_HOOK_ROM);
const finalCleanupRestore = cleanupUpgradePlan.writes.find(write =>
  write.offset === rev0Layout.CLEANUP_HOOK_ROM);
check('all superseded cleanup hooks upgrade back to retail cleanup',
  prematureCleanupRestore && equalBytes(prematureCleanupRestore.bytes,
    OB64.squad.wordsToBytes(C.LEGACY_CLEANUP_ORIGINAL_WORDS)) &&
  finalCleanupRestore && equalBytes(finalCleanupRestore.bytes,
    OB64.squad.wordsToBytes(C.CLEANUP_ORIGINAL_WORDS)));

throws('one-member custom squads fail closed', () =>
  OB64.runtimeOverrides.buildTypedProfileTable([{
    profileId: 1, runtimeKey: scenarioA.runtimeKey, slice: scenarioA.slice,
    terrainSlot: 0,
    members: [{ classId: 5, levelOffsetRaw: 1, cell: 0, cohort: 'A' }],
    equipment: customEquipmentFixture(),
    persuasion: { mode: 'fixed', chance: 10 },
  }]), /two through five/i);
throws('custom formation cell nine is rejected instead of translated at runtime', () =>
  OB64.runtimeOverrides.normalizeCustomProfile({
    profileId: 1, runtimeKey: scenarioA.runtimeKey, slice: scenarioA.slice,
    terrainSlot: 0,
    members: customMembersFixture().map((member, index) =>
      index === 1 ? Object.assign({}, member, { cell: 9 }) : member),
    equipment: customEquipmentFixture(),
  }, 0), /zero through 8|0 through 8|from 0 through 8/i);
throws('duplicate player-leader class bonuses fail closed', () =>
  OB64.runtimeOverrides.normalizeCustomProfile({
    profileId: 1, runtimeKey: scenarioA.runtimeKey, slice: scenarioA.slice,
    terrainSlot: 0, members: customMembersFixture(),
    equipment: customEquipmentFixture(),
    persuasion: { classBonuses: [
      { classId: 5, bonus: 10 }, { classId: 5, bonus: 20 },
    ] },
  }, 0), /cannot repeat/i);
throws('empty encounter-card text fails closed', () =>
  OB64.runtimeOverrides.normalizeCustomProfile(Object.assign({}, customProfiles[0], {
    label: '   ',
  }), 0), /cannot be empty/i);
throws('message control characters fail closed', () =>
  OB64.runtimeOverrides.normalizeCustomProfile(Object.assign({}, customProfiles[0], {
    label: 'Bandits@wait',
  }), 0), /unsupported character/i);
throws('overlong encounter-card text fails closed', () =>
  OB64.runtimeOverrides.normalizeCustomProfile(Object.assign({}, customProfiles[0], {
    label: '1234567890123456789012345',
  }), 0), /at most 24/i);
const uniqueMessageCapacityProfiles = Array.from({ length: C.TYPED_MAX_PROFILES },
  (_, index) => Object.assign({}, customProfiles[0], {
    profileId: index + 1,
    runtimeKey: 1 + Math.floor(index / 10),
    terrainSlot: index % 10,
    label: 'Raiders ' + String(index + 1).padStart(2, '0'),
  }));
throws('typed-profile text allocation fails closed before overlapping the rate resolver', () =>
  OB64.runtimeOverrides.buildTypedProfileTable(uniqueMessageCapacityProfiles, rev0Layout),
  /0x1000-byte typed-profile allocation/i);

console.log('\n-- weighted boundaries and revision profiles --');
function weightedSlot(weights, rng) {
  const remainder = rng % weights.reduce((sum, value) => sum + value, 0);
  if (remainder < weights[0]) return 0;
  if (remainder - weights[0] < weights[1]) return 1;
  return 2;
}
check('weights 1:2:3 select the exact six-remainder boundary pattern',
  [0, 1, 2, 3, 4, 5].map(value => weightedSlot([1, 2, 3], value)).join(',') ===
  '0,1,1,2,2,2');
check('zero-weight slots are unreachable while a positive slot remains',
  Array.from({ length: 20 }, (_, value) => weightedSlot([0, 5, 0], value))
    .every(slot => slot === 1));
throws('zero-total weighted class fails closed', () =>
  OB64.runtimeOverrides.buildDropTable([{ classId: 0x45, weights: [0, 0, 0] }]),
  /zero total/i);

const rev1Layout = OB64.runtimeOverrides.patchLayout(rev1);
const rev1Plan = OB64.runtimeOverrides.buildRuntimeOverrideWrites(
  [], [], 256, { layout: rev1 }, {
    scenarioRateOverrides: scenarioRates,
    weightedDropOverrides: weightedOverrides,
    customNeutralSquads: [],
  }
);
check('Rev 1 rate and drop build targets only its shifted hook addresses',
  rev1Plan.writes.some(write => write.offset === rev1Layout.RATE_HOOK_ROM) &&
  rev1Plan.writes.some(write => write.offset === rev1Layout.DROP_HOOK_ROM) &&
  !rev1Plan.writes.some(write => write.offset === rev0Layout.RATE_HOOK_ROM ||
    write.offset === rev0Layout.DROP_HOOK_ROM));
throws('Rev 1 rejects custom neutral squads until its typed hooks are verified', () =>
  OB64.runtimeOverrides.buildRuntimeOverrideWrites([], [], 256, { layout: rev1 }, {
    scenarioRateOverrides: [], weightedDropOverrides: [], customNeutralSquads: customProfiles,
  }), /unavailable/i);

console.log('\n-- Project round-trip and direct-rate persistence --');
OB64.applyRomLayout(OB64.cloneRomLayout(rev0));
const untouchedSource = OB64.loadROM(masterV64.slice().buffer);
OB64.patch.snapshotOriginal(untouchedSource);
untouchedSource.neutralEncounters.records[scenarioA.slice - 1].rateOverride.normal =
  { mode: 'override', passCount: 77, divisor: 72000 };
const untouchedProject = OB64.patch.collectPatch(untouchedSource);
check('the retired shared-slice model cannot create a new runtime or Project override',
  OB64.runtimeOverrides.collectScenarioRateOverrides(untouchedSource).length === 0 &&
  untouchedProject.summary.neutral_slice_rates_modified === 0 &&
  untouchedProject.summary.neutral_scenario_rates_modified === 0);
const projectSource = OB64.loadROM(masterV64.slice().buffer);
OB64.patch.snapshotOriginal(projectSource);
const projectScenarioA = projectSource.neutralEncounters.scenarioRates.find(row =>
  row.runtimeKey === scenarioA.runtimeKey);
projectScenarioA.rateOverride.normal = { mode: 'disabled', passCount: null, divisor: null };
projectScenarioA.rateOverride.alternate = { mode: 'override', passCount: 9, divisor: 1000 };
projectSource.neutralEncounters.customSquads.push({
  profileId: 1,
  runtimeKey: projectScenarioA.runtimeKey,
  slice: projectScenarioA.slice,
  terrainSlot: 2,
  members: customMembersFixture(),
  equipment: customEquipmentFixture(),
  label: 'Forest Raiders!',
  persuasion: {
    mode: 'fixed', chance: 37, classBonuses: customBonusesFixture(),
  },
  retreat: { hpThreshold: 25 },
  rewards: customRewardsFixture(),
});
const firstDrop = projectSource.creatureDrops.records.find(record => record.isRuntimeActive);
firstDrop.slots[0].weight = 1;
firstDrop.slots[1].weight = 2;
firstDrop.slots[2].weight = 3;
const project = OB64.patch.collectPatch(projectSource);
check('current Project stores only the direct scenario rate, custom squad, and weights',
  project.version === OB64.patch.VERSION &&
  project.summary.neutral_slice_rates_modified === 0 &&
  project.summary.neutral_scenario_rates_modified === 1 &&
  project.summary.custom_neutral_squads_modified === 1 &&
  project.summary.weighted_drop_classes_modified === 1 &&
  project.patches.neutral_encounters.scenario_rates[String(projectScenarioA.runtimeKey)]
    .alternate.pass_count === 9 &&
  project.patches.neutral_encounters.custom_squads[
    projectScenarioA.runtimeKey + ':2'].persuasion.chance === 37 &&
  project.patches.neutral_encounters.custom_squads[
    projectScenarioA.runtimeKey + ':2'].label === 'Forest Raiders!' &&
  project.patches.neutral_encounters.custom_squads[
    projectScenarioA.runtimeKey + ':2'].members[0].cell === 6 &&
  project.patches.neutral_encounters.custom_squads[
    projectScenarioA.runtimeKey + ':2'].members[1].cell === 8 &&
  project.patches.neutral_encounters.custom_squads[
    projectScenarioA.runtimeKey + ':2'].members[3].cell === 0 &&
  project.patches.neutral_encounters.custom_squads[
    projectScenarioA.runtimeKey + ':2'].persuasion.class_bonuses.length === 3 &&
  project.patches.neutral_encounters.custom_squads[
    projectScenarioA.runtimeKey + ':2'].retreat.hp_threshold === 25 &&
  project.patches.neutral_encounters.custom_squads[
    projectScenarioA.runtimeKey + ':2'].rewards.slots[1].weight === 2,
  JSON.stringify(project.summary));
check('runtime collection emits only the scenario whose override box was changed',
  OB64.runtimeOverrides.collectScenarioRateOverrides(projectSource).length === 1 &&
  OB64.runtimeOverrides.collectScenarioRateOverrides(projectSource)[0].runtimeKey ===
    projectScenarioA.runtimeKey);

const projectTarget = OB64.loadROM(masterV64.slice().buffer);
OB64.patch.snapshotOriginal(projectTarget);
const projectDirty = {};
const projectApplied = OB64.patch.applyPatch(projectTarget, cloneJson(project), projectDirty);
const targetScenario = projectTarget.neutralEncounters.scenarioRates.find(row =>
  row.runtimeKey === projectScenarioA.runtimeKey);
check('Project reload retains the exact changed scenario rates and marks their shared owner',
  projectApplied.applied.neutralSliceRates === 0 &&
  projectApplied.applied.neutralScenarioRates === 1 &&
  projectApplied.applied.customNeutralSquads === 1 &&
  projectApplied.applied.weightedDropRates === 1 && projectDirty.neutralRuntime === true &&
  targetScenario.rateOverride.normal.mode === 'disabled' &&
  targetScenario.rateOverride.alternate.passCount === 9 &&
  projectTarget.neutralEncounters.customSquads[0].persuasion.chance === 37 &&
  projectTarget.neutralEncounters.customSquads[0].label === 'Forest Raiders!' &&
  JSON.stringify(projectTarget.neutralEncounters.customSquads[0].members) ===
    JSON.stringify(customMembersFixture()) &&
  JSON.stringify(projectTarget.neutralEncounters.customSquads[0].equipment) ===
    JSON.stringify(customEquipmentFixture()) &&
  JSON.stringify(projectTarget.neutralEncounters.customSquads[0].persuasion.classBonuses) ===
    JSON.stringify(customBonusesFixture()) &&
  projectTarget.neutralEncounters.customSquads[0].retreat.hpThreshold === 25 &&
  JSON.stringify(projectTarget.neutralEncounters.customSquads[0].rewards) ===
    JSON.stringify(customRewardsFixture()));

const retiredSliceProject = cloneJson(project);
retiredSliceProject.patches.neutral_encounters.slice_rates = {};
retiredSliceProject.patches.neutral_encounters.slice_rates[String(projectScenarioA.slice)] = {
  normal: { mode: 'override', pass_count: 77, divisor: 72000 },
  alternate: { mode: 'disabled' },
};
delete retiredSliceProject.patches.neutral_encounters.scenario_rates;
delete retiredSliceProject.patches.neutral_encounters.custom_squads;
const retiredSliceTarget = OB64.loadROM(masterV64.slice().buffer);
OB64.patch.snapshotOriginal(retiredSliceTarget);
const retiredSliceApplied = OB64.patch.applyPatch(
  retiredSliceTarget, retiredSliceProject, {});
check('the retired shared-slice Project field is ignored instead of creating hidden overrides',
  retiredSliceApplied.applied.neutralSliceRates === 0 &&
  OB64.runtimeOverrides.collectScenarioRateOverrides(retiredSliceTarget).length === 0);

console.log(failures ? '\n' + failures + ' FAILURE(S)' : '\nALL TESTS PASSED');
process.exit(failures ? 1 : 0);
